[package]
name = "uptrakit-cli"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "uptrakit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
thiserror = { workspace = true }
hostname = { workspace = true }
time = { workspace = true }
uptrakit-openapi-client = { path = "../../shared/openapi-client" }
uuid = { workspace = true }
serde_yaml_ng = "0.10"
uptrakit-build-info = { path = "../../shared/build-info" }
uptrakit-directories = { path = "../../shared/directories" }

[build-dependencies]
uptrakit-build-info = { path = "../../shared/build-info" }
