[package]
name = "uptrakit-cli"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
thiserror = { workspace = true }
hostname = { workspace = true }
uptrakit-web-api-types = { path = "../../shared/web-api-types" }
serde_yaml_ng = "0.10"
