[package]
name = "uptrakit-cli"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "uptrakit_cli"
path = "src/lib.rs"

[[bin]]
name = "uptrakit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
thiserror = { workspace = true }
hostname = { workspace = true }
time = { workspace = true }
uptrakit-openapi-client = { path = "../../shared/openapi-client" }
uuid = { workspace = true }
serde_yaml_ng = { workspace = true }
uptrakit-build-info = { path = "../../shared/build-info" }
uptrakit-directories = { path = "../../shared/directories" }
uptrakit-shared-types = { workspace = true }

[dev-dependencies]
uptrakit-openapi-client = { path = "../../shared/openapi-client", features = ["mock"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }

[build-dependencies]
uptrakit-build-info = { path = "../../shared/build-info" }

[lints]
workspace = true
