//! RouterOS plugin — `VersionDetector`, `ReleaseFetcher`, `UpdateExecutor`.
//!
//! The plugin downcasts `Arc<dyn HostRuntime>` to [`RouterOsHostRuntime`] to
//! access the typed RouterOS CLI executor and the `allow_reboot` policy flag.

use std::sync::Arc;

use async_trait::async_trait;
use rootcause::prelude::*;
use uptrakit_plugin_infrastructure_core::command::send_output;
use uptrakit_plugin_infrastructure_core::{
    ConfigModel, DiscoveredSoftware, Discoverer, DiscoveryTarget, ExecuteUpdateResult,
    HostCompatibility, HostRequirements, HostRuntime, OutputStreamType,
    PluginConfigValidationError, PluginError, PluginFamily, ReleaseFetcher, Result,
    RouterOsHostRuntime, UpdateExecutor, UpdateOutputSender, UpstreamRelease, Version,
    VersionDetector, declare_plugin,
};
use uptrakit_shared_types::{PluginRole, plugin_ids};

use crate::channel::RouterOsChannel;
use crate::config::RouterOsConfig;
use crate::error::RouterOsError;
use crate::executor::RouterOsUpdateExecutor;
use crate::version::{
    parse_latest_version, parse_resource_version, parse_resource_version_with_display,
};

/// Stable identifier for the synthesized RouterOS software item. Pinned
/// here so tests and runtime can't drift.
const ROUTEROS_PACKAGE_IDENTIFIER: &str = "routeros";

/// Display name for the synthesized RouterOS software item.
const ROUTEROS_DISPLAY_NAME: &str = "MikroTik RouterOS";

/// Plugin for MikroTik RouterOS package management.
///
/// Supports installed version detection (via `/system resource print`),
/// available release fetching (via `/system package update print`), and
/// update execution (download-only or download+reboot based on config/policy).
///
/// **Runtime requirement:** the host runtime must be [`RouterOsHostRuntime`].
/// Any other runtime type causes role methods to return an error.
pub struct RouterOsPlugin {
    config: RouterOsConfig,
    runtime: Arc<dyn HostRuntime>,
}

impl RouterOsPlugin {
    /// Create a new RouterOS plugin, validating the config at construction time.
    pub fn new(
        config: RouterOsConfig,
        runtime: Arc<dyn HostRuntime>,
    ) -> std::result::Result<Self, PluginConfigValidationError> {
        use uptrakit_plugin_infrastructure_core::PluginConfig as _;
        config.validate()?;
        Ok(Self { config, runtime })
    }

    /// Downcast the host runtime to [`RouterOsHostRuntime`].
    ///
    /// Returns an error when the plugin is used with an incompatible runtime.
    fn ros_runtime(&self) -> std::result::Result<&RouterOsHostRuntime, Report<RouterOsError>> {
        self.runtime
            .as_any()
            .downcast_ref::<RouterOsHostRuntime>()
            .ok_or_else(|| {
                report!(RouterOsError::SshExec(
                    "RouterOsPlugin requires RouterOsHostRuntime; downcast failed".to_string()
                ))
            })
    }
}

// ── declare_plugin! ──────────────────────────────────────────────────────────

declare_plugin!(RouterOsPlugin, RouterOsConfig, "package_manager_routeros", {
    display_name: "RouterOS Package Manager",
    family: PluginFamily::Software,
    config_model: ConfigModel::PluginConfig,
    host_requirements: HostRequirements::ROUTER_OS,
    type_settings: true,
    roles: [
        Discoverer { host_requirements: HostRequirements::ROUTER_OS },
        VersionDetector { host_requirements: HostRequirements::ROUTER_OS },
        UpdateExecutor { host_requirements: HostRequirements::ROUTER_OS },
        ReleaseFetcher { host_requirements: HostRequirements::ROUTER_OS },
    ],
});

// ── PluginMeta is generated by declare_plugin! ────────────────────────────────

// ── Discoverer ────────────────────────────────────────────────────────────────

#[async_trait]
impl Discoverer for RouterOsPlugin {
    /// Block cross-runtime invocation explicitly.
    ///
    /// The static `host_requirements` gate at the agent dispatch loop
    /// filters non-ROS hosts before discovery runs in normal operation, but
    /// falls through to this probe on legacy agents that haven't reported
    /// `os_family`. Without this override, `discover_software()` would run,
    /// the `ros_runtime()` downcast would fail, and the dispatch loop would
    /// emit a `tracing::warn!("discovery failed")` per such host per cycle.
    /// Returning `Incompatible` keeps the log path clean and the result
    /// an explicit empty.
    async fn detect_host_compatibility(&self) -> Result<HostCompatibility> {
        if self.ros_runtime().is_err() {
            return Ok(HostCompatibility::Incompatible(
                "RouterOS plugin requires a RouterOsHostRuntime".to_string(),
            ));
        }
        Ok(HostCompatibility::Compatible)
    }

    /// Self-report the RouterOS install as a single featured software item.
    ///
    /// Reuses `RouterOsExecutor::resource_print()` + the
    /// `parse_resource_version_with_display` parser. Returns `Ok(vec![])`
    /// when the version cannot be parsed (matches the trait contract:
    /// omit items with unknown versions).
    ///
    /// One `DiscoveryTarget` carrying all three roles back to this plugin —
    /// the controller's `process_targets_discovery` honors the
    /// package-manager branch and binds the roles to the host without
    /// auto-creating a `plugin_configs` row.
    #[tracing::instrument(skip_all)]
    async fn discover_software(&self) -> Result<Vec<DiscoveredSoftware>> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let output = ros_rt
            .routeros_executor()
            .resource_print()
            .await
            .map_err(|e| report!(e))?;

        let Some((version, display)) = parse_resource_version_with_display(&output) else {
            tracing::debug!(
                "routeros discovery: `version` field absent from /system resource print output; \
                 omitting RouterOS software item"
            );
            return Ok(vec![]);
        };

        // Auto-fill `channel` from the parsed `(stable)` / `(long-term)` /
        // `(testing)` suffix when present, so the host's plugin config
        // matches the router's actual channel without operator action.
        // `reboot: false` by default — discovery is non-destructive; the
        // operator opts into auto-reboot via the form. Combined with the
        // runtime's `allow_reboot` policy gate, freshly-discovered routers
        // default to download-only behavior.
        let channel = RouterOsChannel::from_resource_suffix(&display);
        let plugin_config = serde_json::to_value(RouterOsConfig {
            channel,
            reboot: false,
        })
        .map_err(|e| {
            report!(PluginError::PluginInternal(format!(
                "failed to serialize discovery target plugin_config: {e}"
            )))
        })?;

        let target = DiscoveryTarget {
            plugin_type: plugin_ids::PACKAGE_MANAGER_ROUTEROS.clone(),
            // Package-manager plugins use type_settings, so the controller's
            // `is_package_manager_plugin` branch skips `plugin_configs`
            // find-or-create. The JSON still flows through to
            // `host_software_item_plugin.config` for default per-host
            // behavior.
            plugin_config,
            plugin_config_name: ROUTEROS_DISPLAY_NAME.to_string(),
            roles: vec![
                PluginRole::DetectVersion,
                PluginRole::FetchReleases,
                PluginRole::ExecuteUpdate,
            ],
            package_identifier: None,
            config_override: None,
            execution_site: None,
        };

        Ok(vec![DiscoveredSoftware {
            package_identifier: ROUTEROS_PACKAGE_IDENTIFIER.to_string(),
            name: ROUTEROS_DISPLAY_NAME.to_string(),
            installed_version: version,
            targets: vec![target],
            extra: None,
            qualifier: None,
            plugin_package_identifier: None,
            featured: true,
            installed_display_version: Some(display),
        }])
    }
}

// ── VersionDetector ───────────────────────────────────────────────────────────

#[async_trait]
impl VersionDetector for RouterOsPlugin {
    /// Detect the installed RouterOS version via `/system resource print`.
    ///
    /// Returns `None` when the `version` field is absent from the output (not
    /// a normal case on a healthy router, but handled defensively).
    async fn detect_installed_version(&self, _package_identifier: &str) -> Result<Option<Version>> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let output = ros_rt
            .routeros_executor()
            .resource_print()
            .await
            .map_err(|e| report!(e))?;

        let version = parse_resource_version(&output).map(Version::new);
        Ok(version)
    }
}

// ── ReleaseFetcher ────────────────────────────────────────────────────────────

#[async_trait]
impl ReleaseFetcher for RouterOsPlugin {
    /// Fetch the latest available RouterOS version via `/system package update print`.
    ///
    /// Returns an empty vec when no `latest-version` field is present in the
    /// output (e.g., the router has not yet checked for updates or is already
    /// up to date and the field is absent).
    async fn fetch_releases(&self, _package_identifier: &str) -> Result<Vec<UpstreamRelease>> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let output = ros_rt
            .routeros_executor()
            .package_update_print()
            .await
            .map_err(|e| report!(e))?;

        let Some(latest) = parse_latest_version(&output) else {
            return Err(report!(RouterOsError::VersionUnavailable(
                "latest-version absent from package update print output; \
                 ensure the router has completed a check-for-updates cycle"
                    .to_string()
            ))
            .context_to::<PluginError>());
        };

        let version = Version::new(&latest);
        let release = UpstreamRelease::new(
            version,
            latest.clone(),
            false,
            format!("https://mikrotik.com/download/changelogs/{latest}"),
        );

        Ok(vec![release])
    }
}

// ── UpdateExecutor ────────────────────────────────────────────────────────────

#[async_trait]
impl UpdateExecutor for RouterOsPlugin {
    /// Execute a RouterOS update.
    ///
    /// - Triggers `check-for-updates` on the router.
    /// - Waits 10 seconds for the router to complete the background check.
    /// - Issues `package install` (download + reboot) when both `config.reboot`
    ///   and `runtime.allow_reboot` are true; otherwise `package download`.
    ///
    /// The `package_identifier` and `to_version` parameters are informational
    /// (RouterOS manages all packages as a unit); they are not used directly.
    async fn execute_update(
        &self,
        _package_identifier: &str,
        _to_version: &str,
        _release_info: Option<&uptrakit_plugin_infrastructure_core::types::ReleaseInfo>,
        output_tx: &UpdateOutputSender,
    ) -> Result<ExecuteUpdateResult> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let allow_reboot = ros_rt.allow_reboot;
        let executor = RouterOsUpdateExecutor {
            exec: ros_rt.routeros_executor(),
            reboot: self.config.reboot,
            allow_reboot,
        };

        executor
            .run_update()
            .await
            .map_err(|e| e.context_to::<PluginError>())?;

        let action = if self.config.reboot && allow_reboot {
            "RouterOS update installed; router will reboot"
        } else {
            "RouterOS update downloaded; manual reboot required to apply"
        };

        // Send a summary line to the output stream (best effort).
        send_output(output_tx, action, OutputStreamType::Stdout).await;

        // When reboot is active, the router will restart — mark as resumable
        // so the controller transitions to AwaitingRestart instead of Completed.
        let resumable = self.config.reboot && allow_reboot;
        Ok(ExecuteUpdateResult::new(action, resumable))
    }
}

#[cfg(test)]
mod tests {
    #![expect(
        clippy::assertions_on_result_states,
        reason = "test assertions use assert!(result.is_ok()) / assert!(result.is_err()) pattern"
    )]

    use std::sync::Arc;

    use uptrakit_plugin_infrastructure_core::{
        HostCapabilities, PluginCapability, PluginError, PluginMeta, RouterOsExecutor,
        construct_routeros_host_runtime, host_features,
    };
    use uptrakit_shared_types::OsFamily;

    use super::*;
    use crate::config::RouterOsConfig;

    // ── mock executor ─────────────────────────────────────────────────────────

    struct MockExec {
        resource_output: String,
        package_update_output: String,
    }

    impl MockExec {
        fn new(
            resource_output: impl Into<String>,
            package_update_output: impl Into<String>,
        ) -> Arc<Self> {
            Arc::new(Self {
                resource_output: resource_output.into(),
                package_update_output: package_update_output.into(),
            })
        }
    }

    #[async_trait::async_trait]
    impl RouterOsExecutor for MockExec {
        async fn resource_print(&self) -> std::result::Result<String, PluginError> {
            Ok(self.resource_output.clone())
        }

        async fn routerboard_print(&self) -> std::result::Result<String, PluginError> {
            Ok(String::new())
        }

        async fn license_print(&self) -> std::result::Result<String, PluginError> {
            Ok(String::new())
        }

        async fn check_for_updates(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }

        async fn package_update_print(&self) -> std::result::Result<String, PluginError> {
            Ok(self.package_update_output.clone())
        }

        async fn package_install(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }

        async fn package_download(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    fn routeros_caps() -> HostCapabilities {
        HostCapabilities {
            os_family: Some(OsFamily::RouterOs),
            features: [host_features::ROUTER_OS_CLI].iter().cloned().collect(),
            ..Default::default()
        }
    }

    fn make_plugin(
        resource_output: &str,
        package_update_output: &str,
        reboot: bool,
        allow_reboot: bool,
    ) -> RouterOsPlugin {
        let exec = MockExec::new(resource_output, package_update_output);
        let runtime = construct_routeros_host_runtime(exec, routeros_caps(), allow_reboot);
        let config = RouterOsConfig {
            channel: None,
            reboot,
        };
        RouterOsPlugin::new(config, runtime).expect("plugin construction should succeed")
    }

    // ── construction ─────────────────────────────────────────────────────────

    #[test]
    fn plugin_creation_succeeds_with_valid_config() {
        let exec = MockExec::new("", "");
        let runtime = construct_routeros_host_runtime(exec, routeros_caps(), false);
        let config = RouterOsConfig {
            channel: Some(crate::channel::RouterOsChannel::Stable),
            reboot: false,
        };
        assert!(RouterOsPlugin::new(config, runtime).is_ok());
    }

    // (Previous `plugin_creation_rejects_invalid_channel` test no longer
    // applies: the enum-typed `channel` field rejects invalid values at
    // deserialization time. See `deserialize_rejects_invalid_channel` in
    // `config.rs::tests` for the equivalent guarantee.)

    // ── plugin_type_id ────────────────────────────────────────────────────────

    #[test]
    fn plugin_type_id_is_correct() {
        let plugin = make_plugin("", "", false, false);
        assert_eq!(plugin.plugin_type_id().as_str(), "package_manager_routeros");
    }

    // ── descriptor ───────────────────────────────────────────────────────────

    #[test]
    fn descriptor_has_version_detector_role() {
        assert!(DESCRIPTOR.roles.version_detector.is_some());
    }

    #[test]
    fn descriptor_has_update_executor_role() {
        assert!(DESCRIPTOR.roles.update_executor.is_some());
    }

    #[test]
    fn descriptor_has_release_fetcher_role() {
        assert!(DESCRIPTOR.roles.release_fetcher.is_some());
    }

    #[test]
    fn descriptor_has_discoverer_role() {
        assert!(DESCRIPTOR.roles.discoverer.is_some());
    }

    #[test]
    fn descriptor_has_discover_local_software_capability() {
        // Macro-derived from `Discoverer` in the role list
        // (see infrastructure-core macros.rs:607-614). Regression guard
        // against silently dropping the role.
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::DiscoverLocalSoftware)
        );
    }

    #[test]
    fn descriptor_has_type_settings() {
        assert!(DESCRIPTOR.type_settings.is_some());
    }

    #[test]
    fn descriptor_has_version_detection_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::VersionDetection)
        );
    }

    #[test]
    fn descriptor_has_update_execution_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::UpdateExecution)
        );
    }

    #[test]
    fn descriptor_has_release_fetching_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::ReleaseFetching)
        );
    }

    // ── detect_installed_version ──────────────────────────────────────────────

    #[tokio::test]
    async fn detect_installed_version_parses_output() {
        let plugin = make_plugin(
            "                   version: 7.14.2 (stable)\n     uptime: 3d\n",
            "",
            false,
            false,
        );
        let version = plugin
            .detect_installed_version("routeros")
            .await
            .expect("should succeed");
        assert_eq!(version.map(|v| v.to_string()), Some("7.14.2".to_string()));
    }

    #[tokio::test]
    async fn detect_installed_version_returns_none_when_absent() {
        let plugin = make_plugin("     uptime: 3d\n", "", false, false);
        let version = plugin
            .detect_installed_version("routeros")
            .await
            .expect("should succeed");
        assert!(version.is_none());
    }

    // ── fetch_releases ────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fetch_releases_returns_latest_version() {
        let plugin = make_plugin(
            "",
            "  channel: stable\n  installed-version: 7.14\n  latest-version: 7.15\n",
            false,
            false,
        );
        let releases = plugin
            .fetch_releases("routeros")
            .await
            .expect("should succeed");
        assert_eq!(releases.len(), 1);
        assert_eq!(releases[0].version.to_string(), "7.15");
    }

    #[tokio::test]
    async fn fetch_releases_returns_err_when_no_latest() {
        let plugin = make_plugin(
            "",
            "  channel: stable\n  installed-version: 7.14\n",
            false,
            false,
        );
        let result = plugin.fetch_releases("routeros").await;
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("latest-version absent")
                || format!("{err:?}").contains("VersionUnavailable"),
            "expected VersionUnavailable error, got: {err}"
        );
    }

    // ── ros_runtime downcast failure ──────────────────────────────────────────

    #[tokio::test]
    async fn detect_installed_version_fails_with_wrong_runtime() {
        use uptrakit_plugin_infrastructure_core::{
            HostCapabilities, LocalCommandExecutor, StandardHostRuntime,
        };
        let executor = Arc::new(LocalCommandExecutor);
        let caps = HostCapabilities::default();
        let runtime = Arc::new(StandardHostRuntime::new(executor, caps));
        let config = RouterOsConfig::default();
        // Bypass the PluginConfig::validate step — use config that passes validation.
        // We need to construct via the internal path since ::new validates config,
        // but config is valid, so just use a plain struct construction workaround.
        let plugin = RouterOsPlugin {
            config,
            runtime: runtime as Arc<dyn HostRuntime>,
        };
        let result = plugin.detect_installed_version("routeros").await;
        assert!(result.is_err());
    }

    // ── discover_software ─────────────────────────────────────────────────────

    #[tokio::test]
    async fn discover_returns_one_featured_routeros_item_with_version() {
        let plugin = make_plugin(
            "                   version: 7.14.2 (stable)\n     uptime: 3d\n",
            "",
            false,
            false,
        );
        let items = plugin.discover_software().await.expect("discover ok");
        assert_eq!(items.len(), 1);
        let item = &items[0];
        assert_eq!(item.package_identifier, ROUTEROS_PACKAGE_IDENTIFIER);
        assert_eq!(item.name, ROUTEROS_DISPLAY_NAME);
        assert_eq!(item.installed_version, "7.14.2");
        assert_eq!(
            item.installed_display_version.as_deref(),
            Some("7.14.2 (stable)"),
        );
        assert!(item.featured);
        assert_eq!(item.targets.len(), 1);
    }

    #[tokio::test]
    async fn discover_target_carries_all_three_roles() {
        let plugin = make_plugin(
            "                   version: 7.14.2 (stable)\n",
            "",
            false,
            false,
        );
        let items = plugin.discover_software().await.expect("discover ok");
        let target = &items[0].targets[0];
        assert_eq!(target.plugin_type, plugin_ids::PACKAGE_MANAGER_ROUTEROS);
        assert_eq!(
            target.roles,
            vec![
                PluginRole::DetectVersion,
                PluginRole::FetchReleases,
                PluginRole::ExecuteUpdate,
            ],
            "all three follow-up roles must be assigned to the routeros plugin"
        );
    }

    #[tokio::test]
    async fn discover_target_plugin_config_has_reboot_false_and_parsed_channel() {
        let plugin = make_plugin(
            "                   version: 7.14.2 (stable)\n",
            "",
            false,
            false,
        );
        let items = plugin.discover_software().await.expect("discover ok");
        let target_config: RouterOsConfig =
            serde_json::from_value(items[0].targets[0].plugin_config.clone())
                .expect("target plugin_config must deserialize as RouterOsConfig");
        assert_eq!(target_config.channel, Some(RouterOsChannel::Stable));
        assert!(
            !target_config.reboot,
            "discovery defaults reboot to false (operator opts in via the form)"
        );
    }

    #[tokio::test]
    async fn discover_target_plugin_config_omits_channel_when_suffix_absent() {
        let plugin = make_plugin("                   version: 7.14.2\n", "", false, false);
        let items = plugin.discover_software().await.expect("discover ok");
        let target_config: RouterOsConfig =
            serde_json::from_value(items[0].targets[0].plugin_config.clone())
                .expect("target plugin_config must deserialize as RouterOsConfig");
        assert_eq!(
            target_config.channel, None,
            "discovery does not fabricate a default channel when the router doesn't report one"
        );
        assert!(!target_config.reboot);
    }

    #[tokio::test]
    async fn discover_returns_empty_when_version_absent() {
        let plugin = make_plugin("     uptime: 3d\n", "", false, false);
        let items = plugin.discover_software().await.expect("discover ok");
        assert!(
            items.is_empty(),
            "no version means no software item (matches Discoverer trait contract)"
        );
    }

    #[tokio::test]
    async fn detect_host_compatibility_incompatible_on_wrong_runtime() {
        use uptrakit_plugin_infrastructure_core::{
            HostCapabilities, LocalCommandExecutor, StandardHostRuntime,
        };
        let executor = Arc::new(LocalCommandExecutor);
        let caps = HostCapabilities::default();
        let runtime = Arc::new(StandardHostRuntime::new(executor, caps));
        let plugin = RouterOsPlugin {
            config: RouterOsConfig::default(),
            runtime: runtime as Arc<dyn HostRuntime>,
        };
        let result = plugin
            .detect_host_compatibility()
            .await
            .expect("should return Ok");
        assert!(
            matches!(result, HostCompatibility::Incompatible(_)),
            "wrong runtime must yield Incompatible, got: {result:?}"
        );
    }
}
