//! RouterOS plugin — `VersionDetector`, `ReleaseFetcher`, `UpdateExecutor`.
//!
//! The plugin downcasts `Arc<dyn HostRuntime>` to [`RouterOsHostRuntime`] to
//! access the typed RouterOS CLI executor and the `allow_reboot` policy flag.

use std::sync::Arc;

use async_trait::async_trait;
use rootcause::prelude::*;
use uptrakit_plugin_infrastructure_core::command::send_output;
use uptrakit_plugin_infrastructure_core::{
    ConfigModel, ExecuteUpdateResult, HostRequirements, HostRuntime, OutputStreamType,
    PluginConfigValidationError, PluginError, PluginFamily, ReleaseFetcher, Result,
    RouterOsHostRuntime, UpdateExecutor, UpdateOutputSender, UpstreamRelease, Version,
    VersionDetector, declare_plugin,
};

use crate::config::RouterOsConfig;
use crate::error::RouterOsError;
use crate::executor::RouterOsUpdateExecutor;
use crate::version::{parse_latest_version, parse_resource_version};

/// Plugin for MikroTik RouterOS package management.
///
/// Supports installed version detection (via `/system resource print`),
/// available release fetching (via `/system package update print`), and
/// update execution (download-only or download+reboot based on config/policy).
///
/// **Runtime requirement:** the host runtime must be [`RouterOsHostRuntime`].
/// Any other runtime type causes role methods to return an error.
pub struct RouterOsPlugin {
    config: RouterOsConfig,
    runtime: Arc<dyn HostRuntime>,
}

impl RouterOsPlugin {
    /// Create a new RouterOS plugin, validating the config at construction time.
    pub fn new(
        config: RouterOsConfig,
        runtime: Arc<dyn HostRuntime>,
    ) -> std::result::Result<Self, PluginConfigValidationError> {
        use uptrakit_plugin_infrastructure_core::PluginConfig as _;
        config.validate()?;
        Ok(Self { config, runtime })
    }

    /// Downcast the host runtime to [`RouterOsHostRuntime`].
    ///
    /// Returns an error when the plugin is used with an incompatible runtime.
    fn ros_runtime(&self) -> std::result::Result<&RouterOsHostRuntime, Report<RouterOsError>> {
        self.runtime
            .as_any()
            .downcast_ref::<RouterOsHostRuntime>()
            .ok_or_else(|| {
                report!(RouterOsError::SshExec(
                    "RouterOsPlugin requires RouterOsHostRuntime; downcast failed".to_string()
                ))
            })
    }
}

// ── declare_plugin! ──────────────────────────────────────────────────────────

declare_plugin!(RouterOsPlugin, RouterOsConfig, "package_manager_routeros", {
    display_name: "RouterOS Package Manager",
    family: PluginFamily::Software,
    config_model: ConfigModel::PluginConfig,
    host_requirements: HostRequirements::ROUTER_OS,
    type_settings: true,
    roles: [
        VersionDetector { host_requirements: HostRequirements::ROUTER_OS },
        UpdateExecutor { host_requirements: HostRequirements::ROUTER_OS },
        ReleaseFetcher { host_requirements: HostRequirements::ROUTER_OS },
    ],
});

// ── PluginMeta is generated by declare_plugin! ────────────────────────────────

// ── VersionDetector ───────────────────────────────────────────────────────────

#[async_trait]
impl VersionDetector for RouterOsPlugin {
    /// Detect the installed RouterOS version via `/system resource print`.
    ///
    /// Returns `None` when the `version` field is absent from the output (not
    /// a normal case on a healthy router, but handled defensively).
    async fn detect_installed_version(&self, _package_identifier: &str) -> Result<Option<Version>> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let output = ros_rt
            .routeros_executor()
            .resource_print()
            .await
            .map_err(|e| report!(e))?;

        let version = parse_resource_version(&output).map(Version::new);
        Ok(version)
    }
}

// ── ReleaseFetcher ────────────────────────────────────────────────────────────

#[async_trait]
impl ReleaseFetcher for RouterOsPlugin {
    /// Fetch the latest available RouterOS version via `/system package update print`.
    ///
    /// Returns an empty vec when no `latest-version` field is present in the
    /// output (e.g., the router has not yet checked for updates or is already
    /// up to date and the field is absent).
    async fn fetch_releases(&self, _package_identifier: &str) -> Result<Vec<UpstreamRelease>> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let output = ros_rt
            .routeros_executor()
            .package_update_print()
            .await
            .map_err(|e| report!(e))?;

        let Some(latest) = parse_latest_version(&output) else {
            return Err(report!(RouterOsError::VersionUnavailable(
                "latest-version absent from package update print output; \
                 ensure the router has completed a check-for-updates cycle"
                    .to_string()
            ))
            .context_to::<PluginError>());
        };

        let version = Version::new(&latest);
        let release = UpstreamRelease::new(
            version,
            latest.clone(),
            false,
            format!("https://mikrotik.com/download/changelogs/{latest}"),
        );

        Ok(vec![release])
    }
}

// ── UpdateExecutor ────────────────────────────────────────────────────────────

#[async_trait]
impl UpdateExecutor for RouterOsPlugin {
    /// Execute a RouterOS update.
    ///
    /// - Triggers `check-for-updates` on the router.
    /// - Waits 10 seconds for the router to complete the background check.
    /// - Issues `package install` (download + reboot) when both `config.reboot`
    ///   and `runtime.allow_reboot` are true; otherwise `package download`.
    ///
    /// The `package_identifier` and `to_version` parameters are informational
    /// (RouterOS manages all packages as a unit); they are not used directly.
    async fn execute_update(
        &self,
        _package_identifier: &str,
        _to_version: &str,
        _release_info: Option<&uptrakit_plugin_infrastructure_core::types::ReleaseInfo>,
        output_tx: &UpdateOutputSender,
    ) -> Result<ExecuteUpdateResult> {
        let ros_rt = self
            .ros_runtime()
            .map_err(|e| e.context_to::<PluginError>())?;

        let allow_reboot = ros_rt.allow_reboot;
        let executor = RouterOsUpdateExecutor {
            exec: ros_rt.routeros_executor(),
            reboot: self.config.reboot,
            allow_reboot,
        };

        executor
            .run_update()
            .await
            .map_err(|e| e.context_to::<PluginError>())?;

        let action = if self.config.reboot && allow_reboot {
            "RouterOS update installed; router will reboot"
        } else {
            "RouterOS update downloaded; manual reboot required to apply"
        };

        // Send a summary line to the output stream (best effort).
        send_output(output_tx, action, OutputStreamType::Stdout).await;

        // When reboot is active, the router will restart — mark as resumable
        // so the controller transitions to AwaitingRestart instead of Completed.
        let resumable = self.config.reboot && allow_reboot;
        Ok(ExecuteUpdateResult::new(action, resumable))
    }
}

#[cfg(test)]
mod tests {
    #![expect(
        clippy::assertions_on_result_states,
        reason = "test assertions use assert!(result.is_ok()) / assert!(result.is_err()) pattern"
    )]

    use std::sync::Arc;

    use uptrakit_plugin_infrastructure_core::{
        HostCapabilities, PluginCapability, PluginError, PluginMeta, RouterOsExecutor,
        construct_routeros_host_runtime, host_features,
    };
    use uptrakit_shared_types::OsFamily;

    use super::*;
    use crate::config::RouterOsConfig;

    // ── mock executor ─────────────────────────────────────────────────────────

    struct MockExec {
        resource_output: String,
        package_update_output: String,
    }

    impl MockExec {
        fn new(
            resource_output: impl Into<String>,
            package_update_output: impl Into<String>,
        ) -> Arc<Self> {
            Arc::new(Self {
                resource_output: resource_output.into(),
                package_update_output: package_update_output.into(),
            })
        }
    }

    #[async_trait::async_trait]
    impl RouterOsExecutor for MockExec {
        async fn resource_print(&self) -> std::result::Result<String, PluginError> {
            Ok(self.resource_output.clone())
        }

        async fn routerboard_print(&self) -> std::result::Result<String, PluginError> {
            Ok(String::new())
        }

        async fn license_print(&self) -> std::result::Result<String, PluginError> {
            Ok(String::new())
        }

        async fn check_for_updates(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }

        async fn package_update_print(&self) -> std::result::Result<String, PluginError> {
            Ok(self.package_update_output.clone())
        }

        async fn package_install(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }

        async fn package_download(&self) -> std::result::Result<(), PluginError> {
            Ok(())
        }
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    fn routeros_caps() -> HostCapabilities {
        HostCapabilities {
            os_family: Some(OsFamily::RouterOs),
            features: [host_features::ROUTER_OS_CLI].iter().cloned().collect(),
            ..Default::default()
        }
    }

    fn make_plugin(
        resource_output: &str,
        package_update_output: &str,
        reboot: bool,
        allow_reboot: bool,
    ) -> RouterOsPlugin {
        let exec = MockExec::new(resource_output, package_update_output);
        let runtime = construct_routeros_host_runtime(exec, routeros_caps(), allow_reboot);
        let config = RouterOsConfig {
            channel: None,
            reboot,
        };
        RouterOsPlugin::new(config, runtime).expect("plugin construction should succeed")
    }

    // ── construction ─────────────────────────────────────────────────────────

    #[test]
    fn plugin_creation_succeeds_with_valid_config() {
        let exec = MockExec::new("", "");
        let runtime = construct_routeros_host_runtime(exec, routeros_caps(), false);
        let config = RouterOsConfig {
            channel: Some("stable".to_string()),
            reboot: false,
        };
        assert!(RouterOsPlugin::new(config, runtime).is_ok());
    }

    #[test]
    fn plugin_creation_rejects_invalid_channel() {
        let exec = MockExec::new("", "");
        let runtime = construct_routeros_host_runtime(exec, routeros_caps(), false);
        let config = RouterOsConfig {
            channel: Some("canary".to_string()),
            reboot: false,
        };
        assert!(RouterOsPlugin::new(config, runtime).is_err());
    }

    // ── plugin_type_id ────────────────────────────────────────────────────────

    #[test]
    fn plugin_type_id_is_correct() {
        let plugin = make_plugin("", "", false, false);
        assert_eq!(plugin.plugin_type_id().as_str(), "package_manager_routeros");
    }

    // ── descriptor ───────────────────────────────────────────────────────────

    #[test]
    fn descriptor_has_version_detector_role() {
        assert!(DESCRIPTOR.roles.version_detector.is_some());
    }

    #[test]
    fn descriptor_has_update_executor_role() {
        assert!(DESCRIPTOR.roles.update_executor.is_some());
    }

    #[test]
    fn descriptor_has_release_fetcher_role() {
        assert!(DESCRIPTOR.roles.release_fetcher.is_some());
    }

    #[test]
    fn descriptor_has_no_discoverer_role() {
        assert!(DESCRIPTOR.roles.discoverer.is_none());
    }

    #[test]
    fn descriptor_has_type_settings() {
        assert!(DESCRIPTOR.type_settings.is_some());
    }

    #[test]
    fn descriptor_has_version_detection_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::VersionDetection)
        );
    }

    #[test]
    fn descriptor_has_update_execution_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::UpdateExecution)
        );
    }

    #[test]
    fn descriptor_has_release_fetching_capability() {
        assert!(
            DESCRIPTOR
                .capabilities
                .contains(&PluginCapability::ReleaseFetching)
        );
    }

    // ── detect_installed_version ──────────────────────────────────────────────

    #[tokio::test]
    async fn detect_installed_version_parses_output() {
        let plugin = make_plugin(
            "                   version: 7.14.2 (stable)\n     uptime: 3d\n",
            "",
            false,
            false,
        );
        let version = plugin
            .detect_installed_version("routeros")
            .await
            .expect("should succeed");
        assert_eq!(version.map(|v| v.to_string()), Some("7.14.2".to_string()));
    }

    #[tokio::test]
    async fn detect_installed_version_returns_none_when_absent() {
        let plugin = make_plugin("     uptime: 3d\n", "", false, false);
        let version = plugin
            .detect_installed_version("routeros")
            .await
            .expect("should succeed");
        assert!(version.is_none());
    }

    // ── fetch_releases ────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fetch_releases_returns_latest_version() {
        let plugin = make_plugin(
            "",
            "  channel: stable\n  installed-version: 7.14\n  latest-version: 7.15\n",
            false,
            false,
        );
        let releases = plugin
            .fetch_releases("routeros")
            .await
            .expect("should succeed");
        assert_eq!(releases.len(), 1);
        assert_eq!(releases[0].version.to_string(), "7.15");
    }

    #[tokio::test]
    async fn fetch_releases_returns_err_when_no_latest() {
        let plugin = make_plugin(
            "",
            "  channel: stable\n  installed-version: 7.14\n",
            false,
            false,
        );
        let result = plugin.fetch_releases("routeros").await;
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("latest-version absent")
                || format!("{err:?}").contains("VersionUnavailable"),
            "expected VersionUnavailable error, got: {err}"
        );
    }

    // ── ros_runtime downcast failure ──────────────────────────────────────────

    #[tokio::test]
    async fn detect_installed_version_fails_with_wrong_runtime() {
        use uptrakit_plugin_infrastructure_core::{
            HostCapabilities, LocalCommandExecutor, StandardHostRuntime,
        };
        let executor = Arc::new(LocalCommandExecutor);
        let caps = HostCapabilities::default();
        let runtime = Arc::new(StandardHostRuntime::new(executor, caps));
        let config = RouterOsConfig::default();
        // Bypass the PluginConfig::validate step — use config that passes validation.
        // We need to construct via the internal path since ::new validates config,
        // but config is valid, so just use a plain struct construction workaround.
        let plugin = RouterOsPlugin {
            config,
            runtime: runtime as Arc<dyn HostRuntime>,
        };
        let result = plugin.detect_installed_version("routeros").await;
        assert!(result.is_err());
    }
}
