[package]
name = "uptrakit-service-sdk"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
hostname = { workspace = true }
http = { workspace = true }
uptrakit-backoff = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "time", "sync", "fs", "signal", "macros"] }
tokio-rustls = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v7", "serde"] }
sha2 = { workspace = true }
socket2 = { workspace = true }
webpki-roots = { workspace = true }
x509-parser = { workspace = true }
uptrakit-build-info = { workspace = true }
uptrakit-directories = { workspace = true }
uptrakit-internal-wire = { workspace = true }
uptrakit-shared-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[lints]
workspace = true
