[package]
name = "uptrakit-global-github-provider"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false
description = "Shared GitHub provider contract for global plugins"

[dependencies]
async-trait = { workspace = true }
uptrakit-plugin-infrastructure-core = { workspace = true }

[lints]
workspace = true
