use std::collections::HashMap;

use sea_orm::DbBackend;
use sea_orm_migration::prelude::*;
use sea_orm_migration::schema::*;
use uuid::Uuid;

use super::helpers::{timestamp, timestamp_null};

/// Add a surrogate UUID `id` primary key and nullable `qualifier` column to
/// `host_software_items`, and add `host_software_item_id` FK column to
/// `host_software_item_plugins`.
///
/// ## Motivation
///
/// The original composite PK `(host_id, software_item_id)` prevents a single
/// host from having more than one tracking row per software item. Docker
/// containers require one row per container, so this migration introduces:
///
/// - A surrogate `id UUID` single-column PK.
/// - A nullable `qualifier TEXT` discriminator (container name for Docker,
///   `NULL` for all existing and non-Docker rows).
/// - Two partial unique indexes replacing the old implicit composite PK:
///   - `uix_hsi_unqualified (host_id, software_item_id) WHERE qualifier IS NULL`
///   - `uix_hsi_qualified  (host_id, software_item_id, qualifier) WHERE qualifier IS NOT NULL`
///
/// `host_software_item_plugins` gains a `host_software_item_id UUID NOT NULL`
/// column that references the new PK, replacing the composite FK
/// `(host_id, software_item_id)` → `(host_id, software_item_id)`.
///
/// ## SQLite constraint
///
/// SQLite cannot drop a composite primary key without rebuilding the table.
/// Both tables are therefore rebuilt using the standard 12-step approach:
/// create temp table → copy data → drop original → rename.
///
/// FK enforcement is suspended during the rebuild and restored afterwards.
///
/// ## Crash recovery
///
/// At the start of `up`, leftover `*_new` tables from a previous partial run
/// are dropped before proceeding (State B recovery). If only `*_new` exists
/// (State C), the rename step is applied directly without re-copying.
#[derive(DeriveMigrationName)]
pub(super) struct Migration;

// ---------------------------------------------------------------------------
// Iden definitions
// ---------------------------------------------------------------------------

#[derive(DeriveIden)]
enum HostSoftwareItems {
    Table,
    Id,
    HostId,
    SoftwareItemId,
    Qualifier,
    InstalledVersion,
    InstalledVersionDetectedAt,
    LatestVersion,
    LatestVersionFetchedAt,
    LatestReleaseMetadata,
    LastUpdatedAt,
    LinkedAt,
    UpdateCategory,
}

#[derive(Clone, DeriveIden)]
enum HostSoftwareItemsNew {
    Table,
}

#[derive(Clone, DeriveIden)]
enum HostSoftwareItemsBak {
    Table,
}

#[derive(DeriveIden)]
enum HostSoftwareItemPlugins {
    Table,
    Id,
    HostId,
    SoftwareItemId,
    HostSoftwareItemId,
    PluginConfigId,
    Role,
    Ordinal,
    PackageIdentifier,
    ConfigOverride,
    ExecutionSite,
    CreatedAt,
    UpdatedAt,
}

#[derive(Clone, DeriveIden)]
enum HostSoftwareItemPluginsNew {
    Table,
}

#[derive(Clone, DeriveIden)]
enum HostSoftwareItemPluginsBak {
    Table,
}

#[derive(DeriveIden)]
enum Hosts {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum SoftwareItems {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum PluginConfigs {
    Table,
    Id,
}

// ---------------------------------------------------------------------------
// Column lists shared between INSERT and SELECT during copy
// ---------------------------------------------------------------------------

/// Columns in `host_software_items` excluding the new `id` and `qualifier`
/// (those are supplied by the migration logic, not copied verbatim).
const HSI_COPY_COLS: [HostSoftwareItems; 10] = [
    HostSoftwareItems::HostId,
    HostSoftwareItems::SoftwareItemId,
    HostSoftwareItems::InstalledVersion,
    HostSoftwareItems::InstalledVersionDetectedAt,
    HostSoftwareItems::LatestVersion,
    HostSoftwareItems::LatestVersionFetchedAt,
    HostSoftwareItems::LatestReleaseMetadata,
    HostSoftwareItems::LastUpdatedAt,
    HostSoftwareItems::LinkedAt,
    HostSoftwareItems::UpdateCategory,
    // `qualifier` is always NULL for existing rows.
    // `id` is generated by the migration.
];

/// Columns to read from the old `host_software_item_plugins` table.
const HSIP_COPY_COLS: [HostSoftwareItemPlugins; 11] = [
    HostSoftwareItemPlugins::Id,
    HostSoftwareItemPlugins::HostId,
    HostSoftwareItemPlugins::SoftwareItemId,
    HostSoftwareItemPlugins::PluginConfigId,
    HostSoftwareItemPlugins::Role,
    HostSoftwareItemPlugins::Ordinal,
    HostSoftwareItemPlugins::PackageIdentifier,
    HostSoftwareItemPlugins::ConfigOverride,
    HostSoftwareItemPlugins::ExecutionSite,
    HostSoftwareItemPlugins::CreatedAt,
    HostSoftwareItemPlugins::UpdatedAt,
];

// ---------------------------------------------------------------------------
// Helper: suspend / resume FK enforcement (SQLite only)
// ---------------------------------------------------------------------------

async fn set_foreign_keys(manager: &SchemaManager<'_>, enabled: bool) -> Result<(), DbErr> {
    if manager.get_database_backend() == DbBackend::Sqlite {
        let pragma = if enabled {
            "PRAGMA foreign_keys = ON"
        } else {
            "PRAGMA foreign_keys = OFF"
        };
        manager.get_connection().execute_unprepared(pragma).await?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Table builders
// ---------------------------------------------------------------------------

/// Build the new `host_software_items` schema (with `id` surrogate PK and
/// `qualifier`), targeting `table_name`.
///
/// `fk_suffix` differentiates FK constraint names when creating a temp table
/// alongside the original (MariaDB/InnoDB requires globally unique FK names).
fn build_hsi_table(table_name: impl IntoTableRef + Clone, fk_suffix: &str) -> TableCreateStatement {
    Table::create()
        .table(table_name.clone())
        .col(
            ColumnDef::new(HostSoftwareItems::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(HostSoftwareItems::HostId).uuid().not_null())
        .col(
            ColumnDef::new(HostSoftwareItems::SoftwareItemId)
                .uuid()
                .not_null(),
        )
        .col(ColumnDef::new(HostSoftwareItems::Qualifier).string().null())
        .col(string_null(HostSoftwareItems::InstalledVersion))
        .col(timestamp_null(
            HostSoftwareItems::InstalledVersionDetectedAt,
        ))
        .col(string_null(HostSoftwareItems::LatestVersion))
        .col(timestamp_null(HostSoftwareItems::LatestVersionFetchedAt))
        .col(
            ColumnDef::new(HostSoftwareItems::LatestReleaseMetadata)
                .json_binary()
                .null(),
        )
        .col(timestamp_null(HostSoftwareItems::LastUpdatedAt))
        .col(timestamp(HostSoftwareItems::LinkedAt))
        .col(
            ColumnDef::new(HostSoftwareItems::UpdateCategory)
                .string()
                .not_null()
                .default("unknown"),
        )
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_host_software_items_host{fk_suffix}"))
                .from(table_name.clone(), HostSoftwareItems::HostId)
                .to(Hosts::Table, Hosts::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_host_software_items_software_item{fk_suffix}"))
                .from(table_name, HostSoftwareItems::SoftwareItemId)
                .to(SoftwareItems::Table, SoftwareItems::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .to_owned()
}

/// Build the old `host_software_items` schema (composite PK, no `id`/`qualifier`),
/// targeting `table_name`. Used by `down`.
fn build_hsi_table_old(
    table_name: impl IntoTableRef + Clone,
    fk_suffix: &str,
) -> TableCreateStatement {
    Table::create()
        .table(table_name.clone())
        .col(ColumnDef::new(HostSoftwareItems::HostId).uuid().not_null())
        .col(
            ColumnDef::new(HostSoftwareItems::SoftwareItemId)
                .uuid()
                .not_null(),
        )
        .col(string_null(HostSoftwareItems::InstalledVersion))
        .col(timestamp_null(
            HostSoftwareItems::InstalledVersionDetectedAt,
        ))
        .col(string_null(HostSoftwareItems::LatestVersion))
        .col(timestamp_null(HostSoftwareItems::LatestVersionFetchedAt))
        .col(
            ColumnDef::new(HostSoftwareItems::LatestReleaseMetadata)
                .json_binary()
                .null(),
        )
        .col(timestamp_null(HostSoftwareItems::LastUpdatedAt))
        .col(timestamp(HostSoftwareItems::LinkedAt))
        .col(
            ColumnDef::new(HostSoftwareItems::UpdateCategory)
                .string()
                .not_null()
                .default("unknown"),
        )
        .primary_key(
            Index::create()
                .col(HostSoftwareItems::HostId)
                .col(HostSoftwareItems::SoftwareItemId),
        )
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_host_software_items_host{fk_suffix}"))
                .from(table_name.clone(), HostSoftwareItems::HostId)
                .to(Hosts::Table, Hosts::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_host_software_items_software_item{fk_suffix}"))
                .from(table_name, HostSoftwareItems::SoftwareItemId)
                .to(SoftwareItems::Table, SoftwareItems::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .to_owned()
}

/// Build the new `host_software_item_plugins` schema (with `host_software_item_id`),
/// targeting `table_name`.
fn build_hsip_table(
    table_name: impl IntoTableRef + Clone,
    hsi_target: impl IntoTableRef,
    fk_suffix: &str,
) -> TableCreateStatement {
    Table::create()
        .table(table_name.clone())
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::HostId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::SoftwareItemId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::HostSoftwareItemId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::PluginConfigId)
                .uuid()
                .not_null(),
        )
        .col(string(HostSoftwareItemPlugins::Role))
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::Ordinal)
                .integer()
                .not_null()
                .default(0),
        )
        .col(string(HostSoftwareItemPlugins::PackageIdentifier))
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::ConfigOverride)
                .json_binary()
                .null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::ExecutionSite)
                .string()
                .not_null()
                .default("auto"),
        )
        .col(timestamp(HostSoftwareItemPlugins::CreatedAt))
        .col(timestamp(HostSoftwareItemPlugins::UpdatedAt))
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_hsip_plugin_config{fk_suffix}"))
                .from(table_name.clone(), HostSoftwareItemPlugins::PluginConfigId)
                .to(PluginConfigs::Table, PluginConfigs::Id)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_hsip_host_software_item_id{fk_suffix}"))
                .from(table_name, HostSoftwareItemPlugins::HostSoftwareItemId)
                .to(hsi_target, HostSoftwareItems::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .to_owned()
}

/// Build the old `host_software_item_plugins` schema (composite FK, no
/// `host_software_item_id`), targeting `table_name`. Used by `down`.
fn build_hsip_table_old(
    table_name: impl IntoTableRef + Clone,
    fk_suffix: &str,
) -> TableCreateStatement {
    Table::create()
        .table(table_name.clone())
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::HostId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::SoftwareItemId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::PluginConfigId)
                .uuid()
                .not_null(),
        )
        .col(string(HostSoftwareItemPlugins::Role))
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::Ordinal)
                .integer()
                .not_null()
                .default(0),
        )
        .col(string(HostSoftwareItemPlugins::PackageIdentifier))
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::ConfigOverride)
                .json_binary()
                .null(),
        )
        .col(
            ColumnDef::new(HostSoftwareItemPlugins::ExecutionSite)
                .string()
                .not_null()
                .default("auto"),
        )
        .col(timestamp(HostSoftwareItemPlugins::CreatedAt))
        .col(timestamp(HostSoftwareItemPlugins::UpdatedAt))
        .foreign_key(
            ForeignKey::create()
                .name(format!("fk_hsip_plugin_config{fk_suffix}"))
                .from(table_name.clone(), HostSoftwareItemPlugins::PluginConfigId)
                .to(PluginConfigs::Table, PluginConfigs::Id)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            &mut ForeignKey::create()
                .name(format!("fk_hsip_host_software_item{fk_suffix}"))
                .from_tbl(table_name)
                .from_col(HostSoftwareItemPlugins::HostId)
                .from_col(HostSoftwareItemPlugins::SoftwareItemId)
                .to_tbl(HostSoftwareItems::Table)
                .to_col(HostSoftwareItems::HostId)
                .to_col(HostSoftwareItems::SoftwareItemId)
                .on_delete(ForeignKeyAction::Cascade)
                .to_owned(),
        )
        .to_owned()
}

// ---------------------------------------------------------------------------
// Migration impl
// ---------------------------------------------------------------------------

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        set_foreign_keys(manager, false).await?;

        let db = manager.get_connection();

        // ── Step 1: Rebuild host_software_items ──────────────────────────────

        let hsi_new_exists = manager.has_table("host_software_items_new").await?;
        let hsi_orig_exists = manager.has_table("host_software_items").await?;

        // State B: discard incomplete temp table.
        if hsi_new_exists && hsi_orig_exists {
            manager
                .drop_table(Table::drop().table(HostSoftwareItemsNew::Table).to_owned())
                .await?;
        }

        // Map from (host_id, software_item_id) → new surrogate id.
        // Built during the copy phase; used when copying host_software_item_plugins.
        let mut hsi_id_map: HashMap<(Uuid, Uuid), Uuid> = HashMap::new();

        if hsi_orig_exists {
            // Create the new table.
            manager
                .create_table(build_hsi_table(HostSoftwareItemsNew::Table, "_new"))
                .await?;

            // Read all existing rows.
            let hsi_select = Query::select()
                .columns(HSI_COPY_COLS)
                .from(HostSoftwareItems::Table)
                .to_owned();
            let rows = db.query_all(&hsi_select).await?;

            for row in &rows {
                let host_id: Uuid = row.try_get("", "host_id")?;
                let software_item_id: Uuid = row.try_get("", "software_item_id")?;
                let installed_version: Option<String> = row.try_get("", "installed_version")?;
                let installed_version_detected_at: Option<time::OffsetDateTime> =
                    row.try_get("", "installed_version_detected_at")?;
                let latest_version: Option<String> = row.try_get("", "latest_version")?;
                let latest_version_fetched_at: Option<time::OffsetDateTime> =
                    row.try_get("", "latest_version_fetched_at")?;
                let latest_release_metadata: Option<serde_json::Value> =
                    row.try_get("", "latest_release_metadata")?;
                let last_updated_at: Option<time::OffsetDateTime> =
                    row.try_get("", "last_updated_at")?;
                let linked_at: time::OffsetDateTime = row.try_get("", "linked_at")?;
                let update_category: String = row.try_get("", "update_category")?;

                let new_id = Uuid::now_v7();
                hsi_id_map.insert((host_id, software_item_id), new_id);

                db.execute(
                    &Query::insert()
                        .into_table(HostSoftwareItemsNew::Table)
                        .columns([
                            HostSoftwareItems::Id,
                            HostSoftwareItems::HostId,
                            HostSoftwareItems::SoftwareItemId,
                            HostSoftwareItems::Qualifier,
                            HostSoftwareItems::InstalledVersion,
                            HostSoftwareItems::InstalledVersionDetectedAt,
                            HostSoftwareItems::LatestVersion,
                            HostSoftwareItems::LatestVersionFetchedAt,
                            HostSoftwareItems::LatestReleaseMetadata,
                            HostSoftwareItems::LastUpdatedAt,
                            HostSoftwareItems::LinkedAt,
                            HostSoftwareItems::UpdateCategory,
                        ])
                        .values_panic([
                            new_id.into(),
                            host_id.into(),
                            software_item_id.into(),
                            Option::<String>::None.into(), // qualifier = NULL for all existing rows
                            installed_version.into(),
                            installed_version_detected_at.into(),
                            latest_version.into(),
                            latest_version_fetched_at.into(),
                            latest_release_metadata.into(),
                            last_updated_at.into(),
                            linked_at.into(),
                            update_category.into(),
                        ])
                        .to_owned(),
                )
                .await?;
            }

            // ── Step 2: Rebuild host_software_item_plugins ───────────────────

            let hsip_new_exists = manager.has_table("host_software_item_plugins_new").await?;
            let hsip_orig_exists = manager.has_table("host_software_item_plugins").await?;

            // State B recovery for plugins table.
            if hsip_new_exists && hsip_orig_exists {
                manager
                    .drop_table(
                        Table::drop()
                            .table(HostSoftwareItemPluginsNew::Table)
                            .to_owned(),
                    )
                    .await?;
            }

            if hsip_orig_exists {
                manager
                    .create_table(build_hsip_table(
                        HostSoftwareItemPluginsNew::Table,
                        HostSoftwareItemsNew::Table,
                        "_new",
                    ))
                    .await?;

                let hsip_select = Query::select()
                    .columns(HSIP_COPY_COLS)
                    .from(HostSoftwareItemPlugins::Table)
                    .to_owned();
                let plugin_rows = db.query_all(&hsip_select).await?;

                for row in &plugin_rows {
                    let id: Uuid = row.try_get("", "id")?;
                    let host_id: Uuid = row.try_get("", "host_id")?;
                    let software_item_id: Uuid = row.try_get("", "software_item_id")?;
                    let plugin_config_id: Uuid = row.try_get("", "plugin_config_id")?;
                    let role: String = row.try_get("", "role")?;
                    let ordinal: i32 = row.try_get("", "ordinal")?;
                    let package_identifier: String = row.try_get("", "package_identifier")?;
                    let config_override: Option<serde_json::Value> =
                        row.try_get("", "config_override")?;
                    let execution_site: String = row.try_get("", "execution_site")?;
                    let created_at: time::OffsetDateTime = row.try_get("", "created_at")?;
                    let updated_at: time::OffsetDateTime = row.try_get("", "updated_at")?;

                    let host_software_item_id = hsi_id_map
                        .get(&(host_id, software_item_id))
                        .copied()
                        .ok_or_else(|| {
                            DbErr::Custom(format!(
                                "host_software_item_plugins row {id} references \
                                 (host_id={host_id}, software_item_id={software_item_id}) \
                                 but no matching host_software_item row was found"
                            ))
                        })?;

                    db.execute(
                        &Query::insert()
                            .into_table(HostSoftwareItemPluginsNew::Table)
                            .columns([
                                HostSoftwareItemPlugins::Id,
                                HostSoftwareItemPlugins::HostId,
                                HostSoftwareItemPlugins::SoftwareItemId,
                                HostSoftwareItemPlugins::HostSoftwareItemId,
                                HostSoftwareItemPlugins::PluginConfigId,
                                HostSoftwareItemPlugins::Role,
                                HostSoftwareItemPlugins::Ordinal,
                                HostSoftwareItemPlugins::PackageIdentifier,
                                HostSoftwareItemPlugins::ConfigOverride,
                                HostSoftwareItemPlugins::ExecutionSite,
                                HostSoftwareItemPlugins::CreatedAt,
                                HostSoftwareItemPlugins::UpdatedAt,
                            ])
                            .values_panic([
                                id.into(),
                                host_id.into(),
                                software_item_id.into(),
                                host_software_item_id.into(),
                                plugin_config_id.into(),
                                role.into(),
                                ordinal.into(),
                                package_identifier.into(),
                                config_override.into(),
                                execution_site.into(),
                                created_at.into(),
                                updated_at.into(),
                            ])
                            .to_owned(),
                    )
                    .await?;
                }

                // Drop old plugins table (and its indexes implicitly).
                manager
                    .drop_table(
                        Table::drop()
                            .table(HostSoftwareItemPlugins::Table)
                            .to_owned(),
                    )
                    .await?;
            }
            // else State C: plugins_new already holds the data.

            // Drop original host_software_items.
            manager
                .drop_table(Table::drop().table(HostSoftwareItems::Table).to_owned())
                .await?;
        }
        // else State C for host_software_items: _new already holds the data.

        // ── Step 3: Renames ──────────────────────────────────────────────────

        manager
            .rename_table(
                Table::rename()
                    .table(HostSoftwareItemsNew::Table, HostSoftwareItems::Table)
                    .to_owned(),
            )
            .await?;

        // Rename plugins table only if a _new variant exists (it may not when
        // the original plugins table was empty and State C applied to plugins).
        if manager.has_table("host_software_item_plugins_new").await? {
            manager
                .rename_table(
                    Table::rename()
                        .table(
                            HostSoftwareItemPluginsNew::Table,
                            HostSoftwareItemPlugins::Table,
                        )
                        .to_owned(),
                )
                .await?;
        }

        // ── Step 4: Create indexes ───────────────────────────────────────────

        // Partial unique indexes (SQLite/PostgreSQL) or a single composite
        // unique index (MySQL/MariaDB, which doesn't support partial indexes).
        if manager.get_database_backend() == DbBackend::MySql {
            // MySQL/MariaDB: single composite unique index on (host_id,
            // software_item_id, qualifier). NULLs are considered distinct in
            // MySQL unique indexes, so multiple NULL-qualifier rows per
            // (host_id, software_item_id) are allowed — matching the semantics
            // of the two partial indexes on the other backends.
            manager
                .create_index(
                    Index::create()
                        .name("uix_hsi_host_item_qualifier")
                        .table(HostSoftwareItems::Table)
                        .col(HostSoftwareItems::HostId)
                        .col(HostSoftwareItems::SoftwareItemId)
                        .col(HostSoftwareItems::Qualifier)
                        .unique()
                        .to_owned(),
                )
                .await?;
        } else {
            // SQLite/PostgreSQL: two partial unique indexes.
            manager
                .create_index(
                    Index::create()
                        .name("uix_hsi_unqualified")
                        .table(HostSoftwareItems::Table)
                        .col(HostSoftwareItems::HostId)
                        .col(HostSoftwareItems::SoftwareItemId)
                        .unique()
                        .and_where(Expr::col(HostSoftwareItems::Qualifier).is_null())
                        .to_owned(),
                )
                .await?;

            manager
                .create_index(
                    Index::create()
                        .name("uix_hsi_qualified")
                        .table(HostSoftwareItems::Table)
                        .col(HostSoftwareItems::HostId)
                        .col(HostSoftwareItems::SoftwareItemId)
                        .col(HostSoftwareItems::Qualifier)
                        .unique()
                        .and_where(Expr::col(HostSoftwareItems::Qualifier).is_not_null())
                        .to_owned(),
                )
                .await?;
        }

        // Unique index for plugins: one plugin per role per host_software_item row.
        manager
            .create_index(
                Index::create()
                    .name("uq_hsip_hsi_role_ordinal")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::HostSoftwareItemId)
                    .col(HostSoftwareItemPlugins::Role)
                    .col(HostSoftwareItemPlugins::Ordinal)
                    .unique()
                    .to_owned(),
            )
            .await?;

        // Restore the non-unique lookup index.
        manager
            .create_index(
                Index::create()
                    .name("idx_hsip_plugin_config_id")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::PluginConfigId)
                    .to_owned(),
            )
            .await?;

        // Restore lookup index on (host_id, software_item_id).
        manager
            .create_index(
                Index::create()
                    .name("idx_hsip_host_item")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::HostId)
                    .col(HostSoftwareItemPlugins::SoftwareItemId)
                    .to_owned(),
            )
            .await?;

        // Restore category index on host_software_items.
        manager
            .create_index(
                Index::create()
                    .name("idx_hsi_host_category")
                    .table(HostSoftwareItems::Table)
                    .col(HostSoftwareItems::HostId)
                    .col(HostSoftwareItems::UpdateCategory)
                    .to_owned(),
            )
            .await?;

        set_foreign_keys(manager, true).await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        set_foreign_keys(manager, false).await?;

        let db = manager.get_connection();

        // ── Step 1: Rebuild host_software_items (old schema) ─────────────────

        let hsi_bak_exists = manager.has_table("host_software_items_bak").await?;
        let hsi_orig_exists = manager.has_table("host_software_items").await?;

        if hsi_bak_exists && hsi_orig_exists {
            manager
                .drop_table(Table::drop().table(HostSoftwareItemsBak::Table).to_owned())
                .await?;
        }

        if hsi_orig_exists {
            manager
                .create_table(build_hsi_table_old(HostSoftwareItemsBak::Table, "_bak"))
                .await?;

            // Read from the new schema (has `id` and `qualifier`); write to old
            // schema dropping qualified rows (qualifier IS NOT NULL) as they did
            // not exist in the old schema.
            let hsi_down_select = Query::select()
                .columns(HSI_COPY_COLS) // excludes id and qualifier
                .from(HostSoftwareItems::Table)
                .and_where(Expr::col(HostSoftwareItems::Qualifier).is_null())
                .to_owned();
            let rows = db.query_all(&hsi_down_select).await?;

            for row in &rows {
                let host_id: Uuid = row.try_get("", "host_id")?;
                let software_item_id: Uuid = row.try_get("", "software_item_id")?;
                let installed_version: Option<String> = row.try_get("", "installed_version")?;
                let installed_version_detected_at: Option<time::OffsetDateTime> =
                    row.try_get("", "installed_version_detected_at")?;
                let latest_version: Option<String> = row.try_get("", "latest_version")?;
                let latest_version_fetched_at: Option<time::OffsetDateTime> =
                    row.try_get("", "latest_version_fetched_at")?;
                let latest_release_metadata: Option<serde_json::Value> =
                    row.try_get("", "latest_release_metadata")?;
                let last_updated_at: Option<time::OffsetDateTime> =
                    row.try_get("", "last_updated_at")?;
                let linked_at: time::OffsetDateTime = row.try_get("", "linked_at")?;
                let update_category: String = row.try_get("", "update_category")?;

                db.execute(
                    &Query::insert()
                        .into_table(HostSoftwareItemsBak::Table)
                        .columns(HSI_COPY_COLS)
                        .values_panic([
                            host_id.into(),
                            software_item_id.into(),
                            installed_version.into(),
                            installed_version_detected_at.into(),
                            latest_version.into(),
                            latest_version_fetched_at.into(),
                            latest_release_metadata.into(),
                            last_updated_at.into(),
                            linked_at.into(),
                            update_category.into(),
                        ])
                        .to_owned(),
                )
                .await?;
            }

            // ── Step 2: Rebuild host_software_item_plugins (old schema) ───────

            let hsip_bak_exists = manager.has_table("host_software_item_plugins_bak").await?;
            let hsip_orig_exists = manager.has_table("host_software_item_plugins").await?;

            if hsip_bak_exists && hsip_orig_exists {
                manager
                    .drop_table(
                        Table::drop()
                            .table(HostSoftwareItemPluginsBak::Table)
                            .to_owned(),
                    )
                    .await?;
            }

            if hsip_orig_exists {
                manager
                    .create_table(build_hsip_table_old(
                        HostSoftwareItemPluginsBak::Table,
                        "_bak",
                    ))
                    .await?;

                let hsip_down_select = Query::select()
                    .columns(HSIP_COPY_COLS) // excludes host_software_item_id
                    .from(HostSoftwareItemPlugins::Table)
                    .to_owned();
                let plugin_rows = db.query_all(&hsip_down_select).await?;

                for row in &plugin_rows {
                    let id: Uuid = row.try_get("", "id")?;
                    let host_id: Uuid = row.try_get("", "host_id")?;
                    let software_item_id: Uuid = row.try_get("", "software_item_id")?;
                    let plugin_config_id: Uuid = row.try_get("", "plugin_config_id")?;
                    let role: String = row.try_get("", "role")?;
                    let ordinal: i32 = row.try_get("", "ordinal")?;
                    let package_identifier: String = row.try_get("", "package_identifier")?;
                    let config_override: Option<serde_json::Value> =
                        row.try_get("", "config_override")?;
                    let execution_site: String = row.try_get("", "execution_site")?;
                    let created_at: time::OffsetDateTime = row.try_get("", "created_at")?;
                    let updated_at: time::OffsetDateTime = row.try_get("", "updated_at")?;

                    db.execute(
                        &Query::insert()
                            .into_table(HostSoftwareItemPluginsBak::Table)
                            .columns(HSIP_COPY_COLS)
                            .values_panic([
                                id.into(),
                                host_id.into(),
                                software_item_id.into(),
                                plugin_config_id.into(),
                                role.into(),
                                ordinal.into(),
                                package_identifier.into(),
                                config_override.into(),
                                execution_site.into(),
                                created_at.into(),
                                updated_at.into(),
                            ])
                            .to_owned(),
                    )
                    .await?;
                }

                manager
                    .drop_table(
                        Table::drop()
                            .table(HostSoftwareItemPlugins::Table)
                            .to_owned(),
                    )
                    .await?;
            }

            manager
                .drop_table(Table::drop().table(HostSoftwareItems::Table).to_owned())
                .await?;
        }

        // ── Step 3: Renames ──────────────────────────────────────────────────

        manager
            .rename_table(
                Table::rename()
                    .table(HostSoftwareItemsBak::Table, HostSoftwareItems::Table)
                    .to_owned(),
            )
            .await?;

        if manager.has_table("host_software_item_plugins_bak").await? {
            manager
                .rename_table(
                    Table::rename()
                        .table(
                            HostSoftwareItemPluginsBak::Table,
                            HostSoftwareItemPlugins::Table,
                        )
                        .to_owned(),
                )
                .await?;
        }

        // ── Step 4: Restore old indexes ──────────────────────────────────────

        manager
            .create_index(
                Index::create()
                    .name("uq_hsip_host_item_role_ordinal")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::HostId)
                    .col(HostSoftwareItemPlugins::SoftwareItemId)
                    .col(HostSoftwareItemPlugins::Role)
                    .col(HostSoftwareItemPlugins::Ordinal)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_hsip_plugin_config_id")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::PluginConfigId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_hsip_host_item")
                    .table(HostSoftwareItemPlugins::Table)
                    .col(HostSoftwareItemPlugins::HostId)
                    .col(HostSoftwareItemPlugins::SoftwareItemId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_hsi_host_category")
                    .table(HostSoftwareItems::Table)
                    .col(HostSoftwareItems::HostId)
                    .col(HostSoftwareItems::UpdateCategory)
                    .to_owned(),
            )
            .await?;

        set_foreign_keys(manager, true).await?;

        Ok(())
    }
}
