[package]
name = "uptrakit-web-api"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = []
swagger-ui = ["dep:utoipa-swagger-ui"]
db-sqlite = ["sea-orm/sqlx-sqlite"]
db-postgres = ["sea-orm/sqlx-postgres"]
db-mysql = ["sea-orm/sqlx-mysql"]

[dependencies]
axum = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
ipnet = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
time = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
uptrakit-directories = { path = "../../shared/directories" }
uptrakit-shared-db = { path = "../../shared/db" }
uptrakit-internal-wire = { path = "../../shared/wire" }
uptrakit-provider-core = { path = "../../providers/core" }
uptrakit-provider-registry = { path = "../../providers/registry" }
argon2 = { version = "0.5", features = ["std"] }
rand = { workspace = true }
client-ip = { version = "0.2", features = ["forwarded-header"] }
x509-parser = { workspace = true }
base64 = "0.22"
sha2 = { workspace = true }
uptrakit-web-api-types = { path = "../../shared/web-api-types", features = ["openapi"] }
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-axum = "0.2"
openidconnect = "4"
url = { workspace = true }
urlencoding = "2"
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs"] }
axum-server = { workspace = true }
hostname = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
utoipa-swagger-ui = { version = "9.0", features = ["axum"], optional = true }
x509-ocsp = { workspace = true }
der = { workspace = true }
spki = { workspace = true }
x509-cert = { workspace = true }
const-oid = { workspace = true }
aws-lc-rs = { workspace = true }
semver = { workspace = true }
tokio-util = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tower = { workspace = true }
http-body-util = "0.1"
strum = { workspace = true }
