[package]
name = "uptrakit-plugin-releases-forgejo"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["http-client"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["parsing"] }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
async-trait = { workspace = true }
uptrakit-shared-types = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
