[package]
name = "uptrakit-mqtt"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
rootcause = { workspace = true }
rumqttc = { version = "0.25.1", features = ["websocket"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uptrakit-web-api-types = { path = "../../shared/web-api-types" }
