[package]
name = "uptrakit-plugin-enhancement-dashboard-icons"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
parking_lot = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
uptrakit-global-github-provider = { workspace = true }
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["catalog"] }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
