[package]
name = "uptrakit-shared-db"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
aws-lc-rs = { workspace = true }
rand = { workspace = true }
rootcause = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uptrakit-shared-macros = { workspace = true }
uptrakit-shared-types = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
sea-orm = { workspace = true, features = ["mock"] }
tokio = { workspace = true }
