[package]
name = "uptrakit-shared-db"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
aws-lc-rs = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
