//! Bootstrap command: automates remote host setup (user creation, SSH key
//! deployment, sudoers configuration) and saves the host entry to the local
//! database.

use std::path::Path;
use std::sync::Arc;
use std::time::Duration;

use rootcause::prelude::*;
use sea_orm::DatabaseConnection;
use uptrakit_crypto::EncryptedString;
use uptrakit_plugin_infrastructure_registry::PluginRegistry;

use uptrakit_plugin_infrastructure_proxmox::pve_setup;

use crate::commands::sudoers::{
    ResolvedSudoCommand, SudoersContent, detect_is_root, install_helper_script,
    resolve_command_path, write_sudoers_file,
};
use crate::error::{Error, Result};
use crate::host_ops::{self, AddHostParams};
use crate::remote_exec::SshRemoteExecutor;
use crate::ssh_executor::SshCommandExecutor;
use crate::ssh_key;
use crate::ssh_transport::{self, AuthMethod, SshConnectionConfig, SshSession};

/// Maximum length for POSIX usernames.
const MAX_USERNAME_LEN: usize = 32;

/// Default SSH connect timeout.
const CONNECT_TIMEOUT: Duration = Duration::from_secs(30);

// ── Bootstrap parameters ─────────────────────────────────────────────

/// Parameters for the bootstrap workflow, mirroring CLI args.
pub struct BootstrapParams {
    pub name: String,
    pub hostname: String,
    pub port: i32,
    pub auth_username: String,
    pub auth_password: Option<String>,
    pub auth_private_key_pem: Option<String>,
    /// Use the local SSH agent for authentication (detected from `SSH_AUTH_SOCK`).
    pub use_ssh_agent: bool,
    pub target_username: String,
    pub target_private_key_pem: Option<String>,
    pub host_key_fingerprint: Option<String>,
    /// When `true`, `host_key_fingerprint` must be `Some` and TOFU is disabled.
    pub strict_host_key_checking: bool,
    /// Write `NOPASSWD: ALL` instead of specific command entries.
    ///
    /// Less secure; use only when no plugin commands can be resolved on the
    /// remote host or during development.
    pub allow_all: bool,
    /// Pre-generated UUID for the new host DB entry.
    ///
    /// Generated by the caller before `run_bootstrap` so that the same UUID
    /// can be embedded in the `authorized_keys` comment for identification.
    pub host_id: uuid::Uuid,
    /// Service UUID for the `authorized_keys` comment.  `None` when the
    /// service has not yet been enrolled.
    pub service_id: Option<uuid::Uuid>,
    /// Tenant UUID for PVE API credential naming.  `None` when the tenant
    /// ID has not yet been received from the controller.
    pub tenant_id: Option<uuid::Uuid>,
    /// Remove existing Uptrakit-managed keys from `authorized_keys` before
    /// writing the new entry.
    pub remove_stale_keys: bool,
}

/// Result of a successful bootstrap, carrying metadata for the event loop.
pub struct BootstrapResult {
    /// Whether the bootstrapped host is a Proxmox VE node.
    pub is_pve_node: bool,
    /// PVE API credentials (api_url, api_token) if auto-created on a new cluster.
    pub pve_credentials: Option<pve_setup::PveCredentials>,
    /// Existing PVE plugin config ID when the cluster was already configured
    /// by a previous bootstrap. The event loop should update the new host's
    /// `pve_plugin_config_id` directly instead of sending `ReportPluginConfig`.
    pub existing_pve_plugin_config_id: Option<String>,
}

// ── Main orchestrator ────────────────────────────────────────────────

/// Run the full bootstrap workflow.
pub async fn run_bootstrap(state_dir: &Path, params: BootstrapParams) -> Result<BootstrapResult> {
    // 1. VALIDATE INPUTS
    if params.strict_host_key_checking && params.host_key_fingerprint.is_none() {
        bail!(Error::InvalidInput(
            "--strict-host-key-checking requires --host-key-fingerprint to be provided".to_string()
        ));
    }

    validate_posix_username(&params.auth_username)?;
    validate_posix_username(&params.target_username)?;

    if params.auth_password.is_none()
        && params.auth_private_key_pem.is_none()
        && !params.use_ssh_agent
    {
        bail!(Error::InvalidInput(
            "no authentication method available: use --auth-password, \
             --auth-private-key-file, or ensure SSH_AUTH_SOCK is set for \
             SSH agent forwarding"
                .to_string()
        ));
    }

    // Fail fast: check host name is not in DB.
    let db = crate::db::init_db(state_dir).await.map_err(|e| {
        report!(Error::Database(sea_orm::DbErr::Custom(format!(
            "failed to initialize local database: {e}"
        ))))
    })?;
    let existing = host_ops::find_host(&db, &params.name).await?;
    if existing.is_some() {
        bail!(Error::HostNameConflict(params.name.clone()));
    }

    // 2. PREPARE KEY MATERIAL
    let (target_private_pem, target_public_openssh, generated_key) =
        match &params.target_private_key_pem {
            Some(pem) => {
                let pubkey = ssh_key::extract_public_key_openssh(pem)?;
                (pem.clone(), pubkey, false)
            }
            None => {
                println!("Generating Ed25519 keypair for target user...");
                let (priv_pem, pub_openssh) = ssh_key::generate_ed25519_keypair()?;
                (priv_pem, pub_openssh, true)
            }
        };

    let key_type = ssh_key::detect_key_type(&target_private_pem)?;

    // 3. CONNECT & AUTHENTICATE (as auth_username)
    let auth = match (
        &params.auth_password,
        &params.auth_private_key_pem,
        params.use_ssh_agent,
    ) {
        (Some(password), _, _) => AuthMethod::Password(password),
        (_, Some(pem), _) => AuthMethod::PrivateKey(pem),
        (_, _, true) => AuthMethod::Agent,
        _ => bail!(Error::InvalidInput(
            "no authentication method available".to_string()
        )),
    };

    let port = u16::try_from(params.port).map_err(|_| {
        report!(Error::InvalidInput(format!(
            "port must be 0-65535, got {}",
            params.port
        )))
    })?;

    let config = SshConnectionConfig {
        hostname: params.hostname.clone(),
        port,
        connect_timeout: CONNECT_TIMEOUT,
    };

    println!(
        "Connecting to {}:{} as '{}'...",
        params.hostname, port, params.auth_username
    );

    let (session, observed_fp) = ssh_transport::connect_and_authenticate(
        &config,
        &params.auth_username,
        &auth,
        params.host_key_fingerprint.as_deref(),
    )
    .await?;

    // Wrap in Arc so the session can be shared with the plugin executor used
    // for host-compatibility checks without copying any state.
    let session = Arc::new(session);

    if params.host_key_fingerprint.is_none() {
        println!("Host key (TOFU): {observed_fp}");
    }

    // Build a RemoteExecutor for the sudoers/detection functions.
    let executor = SshRemoteExecutor::new(Arc::clone(&session));

    // 4. Detect if auth user is root
    let is_root = detect_is_root(&executor).await?;
    let use_sudo = !is_root;

    if use_sudo {
        // Verify auth user has sudo access.
        let sudo_check = session.exec_command("sudo -n true").await?;
        if sudo_check.exit_code != 0 {
            bail!(Error::SshCommand(format!(
                "auth user '{}' does not have passwordless sudo access (exit code {}). \
                 Bootstrap requires sudo privileges on the remote host.",
                params.auth_username, sudo_check.exit_code
            )));
        }
    }

    // 5. REMOTE SETUP
    let target_same_as_auth = params.target_username == params.auth_username;

    if !target_same_as_auth {
        // Check if target user exists.
        let cmd = cmd_check_user_exists(&params.target_username, use_sudo);
        let user_check = session.exec_command(&cmd).await?;

        if user_check.exit_code != 0 {
            println!("Creating user '{}'...", params.target_username);
            let cmd = cmd_create_user(&params.target_username, use_sudo);
            let create_result = session.exec_command(&cmd).await?;
            if create_result.exit_code != 0 {
                bail!(Error::SshCommand(format!(
                    "failed to create user '{}': {}",
                    params.target_username,
                    create_result.stderr.trim()
                )));
            }
        } else {
            println!(
                "User '{}' already exists, skipping creation.",
                params.target_username
            );
        }
    }

    // Detect home directory.
    let home_cmd = cmd_detect_home(&params.target_username, use_sudo);
    let home_result = session.exec_command(&home_cmd).await?;
    let home_dir = home_result.stdout.trim().to_string();
    if home_dir.is_empty() {
        bail!(Error::SshCommand(format!(
            "could not determine home directory for user '{}'",
            params.target_username
        )));
    }

    // 5. DEPLOY authorized_keys.
    println!("Deploying SSH public key...");

    // 5a. Build the authorized_keys comment.
    //
    // The comment encodes the host UUID (always present — pre-generated by
    // the caller) and the service UUID (present when the agent is already
    // enrolled) for easy identification.
    //
    // Format:
    //   uptrakit-host:<host_id>                          (no service UUID)
    //   uptrakit-svc:<service_id>-host:<host_id>         (service UUID known)
    let service_comment = match &params.service_id {
        Some(svc_id) => format!("uptrakit-svc:{svc_id}-host:{}", params.host_id),
        None => format!("uptrakit-host:{}", params.host_id),
    };

    // Strip any trailing comment from the raw public key so we control the
    // comment field ourselves (first two whitespace-separated tokens only).
    let stripped_pubkey = target_public_openssh
        .split_whitespace()
        .take(2)
        .collect::<Vec<_>>()
        .join(" ");

    // 5b. Read existing authorized_keys from remote.
    let read_cmd = cmd_read_authorized_keys(&home_dir, use_sudo);
    let read_result = session.exec_command(&read_cmd).await?;
    let existing = parse_existing_authorized_keys(&read_result.stdout);

    // 5c. Compute auto-removal candidates: keys written by this service on
    //     previous bootstrap runs.  These are removed unconditionally (no
    //     flag required) whenever a service UUID is available.  This keeps
    //     authorized_keys clean when the same service re-bootstraps a machine
    //     (e.g. after key rotation or host reassignment) without affecting
    //     keys that belong to other Uptrakit services or external users.
    let same_service_lines: Vec<String> = params
        .service_id
        .as_ref()
        .map(|svc_id| {
            existing
                .all_key_lines
                .iter()
                .filter(|l| is_same_service_key_line(l, svc_id))
                .cloned()
                .collect()
        })
        .unwrap_or_default();

    // 5d. Determine which additional lines are stale under --remove-stale-keys.
    //     For the `uptrakit` target user all existing entries are considered
    //     Uptrakit-managed (the account is exclusively managed by the agent).
    //     For other users only entries whose comment starts with `uptrakit`
    //     are treated as stale.
    let stale_lines: Vec<String> = if params.target_username == "uptrakit" {
        existing.all_key_lines.clone()
    } else {
        existing.uptrakit_key_lines.clone()
    };

    // 5e. Print notice for auto-removed (same-service) keys.
    if !same_service_lines.is_empty() {
        println!(
            "Removing {} key(s) written by this service on a previous bootstrap...",
            same_service_lines.len()
        );
        for line in &same_service_lines {
            println!("  {line}");
        }
    }

    // 5f. Print notice for remaining stale keys not covered by auto-removal.
    let remaining_stale: Vec<&String> = stale_lines
        .iter()
        .filter(|l| !same_service_lines.contains(l))
        .collect();
    if !remaining_stale.is_empty() {
        let uptrakit_user_note = if params.target_username == "uptrakit" {
            " — all are considered Uptrakit-managed"
        } else {
            ""
        };
        println!(
            "NOTE: Found {} existing key(s) in authorized_keys{uptrakit_user_note}:",
            remaining_stale.len()
        );
        for line in &remaining_stale {
            println!("  {line}");
        }
        if !params.remove_stale_keys {
            println!("      Pass --remove-stale-keys to remove them before writing the new key.");
        }
    }

    // 5g. Build the unified set of lines to remove in this run:
    //       - always: same_service_lines
    //       - with --remove-stale-keys: stale_lines (superset of same_service_lines)
    let mut to_remove: std::collections::HashSet<&str> =
        same_service_lines.iter().map(String::as_str).collect();
    if params.remove_stale_keys {
        for l in &stale_lines {
            to_remove.insert(l.as_str());
        }
    }

    // 5h. Write the authorized_keys file.
    if to_remove.is_empty() {
        // No removals: append the new key entry (also creates .ssh if absent).
        let ak_cmd = cmd_setup_authorized_keys(
            &home_dir,
            &stripped_pubkey,
            &params.target_username,
            use_sudo,
            &service_comment,
        );
        let ak_result = session.exec_command(&ak_cmd).await?;
        if ak_result.exit_code != 0 {
            bail!(Error::SshCommand(format!(
                "failed to deploy authorized_keys: {}",
                ak_result.stderr.trim()
            )));
        }
    } else {
        // Removals required: rewrite the entire file atomically.
        if params.remove_stale_keys && !remaining_stale.is_empty() {
            let qualifier = if same_service_lines.is_empty() {
                ""
            } else {
                "additional "
            };
            println!(
                "Removing {}{} stale key(s) from authorized_keys...",
                qualifier,
                remaining_stale.len()
            );
        }

        let keep_lines: Vec<&str> = existing
            .all_key_lines
            .iter()
            .map(String::as_str)
            .filter(|l| !to_remove.contains(l))
            .collect();

        let new_entry =
            format!("{AUTHORIZED_KEYS_RESTRICTIONS} {stripped_pubkey} {service_comment}");
        let new_content = if keep_lines.is_empty() {
            format!("{new_entry}\n")
        } else {
            format!("{}\n{new_entry}\n", keep_lines.join("\n"))
        };

        let write_cmd =
            cmd_write_authorized_keys(&home_dir, &new_content, &params.target_username, use_sudo);
        let write_result = session.exec_command(&write_cmd).await?;
        if write_result.exit_code != 0 {
            bail!(Error::SshCommand(format!(
                "failed to write authorized_keys: {}",
                write_result.stderr.trim()
            )));
        }
    }

    // Set up sudoers (specific commands per registered plugins).
    //
    // Run host-compatibility checks via an SSH executor so that only the
    // commands applicable to *this* host are included.  For example, the
    // Proxmox Helper Scripts plugin's helper scripts are only installed on
    // Proxmox VE nodes; on Flatcar Linux (read-only /usr/local/bin) they
    // would fail.  The SSH executor is dropped after the call so the session
    // Arc refcount returns to 1 before we call `disconnect_shared`.
    println!("Configuring sudoers...");
    let ssh_executor = Arc::new(SshCommandExecutor::new(Arc::clone(&session)))
        as Arc<dyn uptrakit_command::CommandExecutor>;
    let plugin_sudo_cmds = PluginRegistry::compatible_sudo_commands_for_host(ssh_executor).await;
    let mut resolved: Vec<ResolvedSudoCommand> = Vec::new();

    for (_plugin_type, entries) in &plugin_sudo_cmds {
        for entry in entries {
            if let Some(helper) = &entry.helper_script {
                // Install the helper script then use its known path directly
                // as the sudoers command — no `command -v` resolution needed.
                println!("  Installing helper script '{}'...", helper.install_path);
                install_helper_script(&executor, helper, use_sudo).await?;
                resolved.push(ResolvedSudoCommand {
                    command_path: helper.install_path.to_string(),
                    explanation: entry.explanation.clone(),
                    needs_setenv: entry.needs_setenv,
                });
            } else {
                match resolve_command_path(&executor, &entry.command).await? {
                    Some(path) => {
                        tracing::debug!(command = %entry.command, path = %path, "resolved command path");
                        resolved.push(ResolvedSudoCommand {
                            command_path: path,
                            explanation: entry.explanation.clone(),
                            needs_setenv: entry.needs_setenv,
                        });
                    }
                    None => {
                        tracing::debug!(
                            command = %entry.command,
                            "command not found on remote host, skipping"
                        );
                    }
                }
            }
        }
    }

    let sudoers_content: Option<SudoersContent> = if !resolved.is_empty() {
        Some(SudoersContent::SpecificCommands(resolved))
    } else if params.allow_all {
        println!("  No plugin commands resolved; using NOPASSWD: ALL (--allow-all).");
        Some(SudoersContent::AllCommands)
    } else {
        println!(
            "  No plugin-specific commands found for this host; no sudoers file will be written."
        );
        println!("  Install supported tools or re-run with --allow-all.");
        None
    };

    if let Some(ref content) = sudoers_content {
        write_sudoers_file(&executor, &params.target_username, content, use_sudo).await?;
    }

    // 5b. DETECT PVE NODE
    let is_pve_node = match pve_setup::detect_pve_node(&executor).await {
        Ok(detected) => {
            if detected {
                println!("Detected Proxmox VE node.");
            }
            detected
        }
        Err(e) => {
            tracing::debug!(error = %e, "PVE detection failed, treating as non-PVE host");
            false
        }
    };

    // 5c. CREATE PVE API CREDENTIALS (if PVE node detected)
    let (pve_credentials, existing_pve_plugin_config_id) = if is_pve_node {
        create_or_reuse_pve_credentials(&executor, &db, &params.tenant_id).await
    } else {
        (None, None)
    };

    // 6. DISCONNECT auth session.
    SshSession::disconnect_shared(session).await;

    // 7. VERIFY — reconnect as target_username with target key.
    println!("Verifying connectivity as '{}'...", params.target_username);

    let verify_config = SshConnectionConfig {
        hostname: params.hostname.clone(),
        port,
        connect_timeout: CONNECT_TIMEOUT,
    };

    let (verify_session, _) = ssh_transport::connect_and_authenticate(
        &verify_config,
        &params.target_username,
        &AuthMethod::PrivateKey(&target_private_pem),
        Some(&observed_fp),
    )
    .await
    .map_err(|e| {
        report!(Error::BootstrapVerification(format!(
            "failed to connect as target user '{}': {e}. \
             The remote host has been partially configured (user created, \
             key deployed, sudoers written). Manual cleanup may be required.",
            params.target_username
        )))
    })?;

    verify_remote(
        &verify_session,
        &params.target_username,
        sudoers_content.is_some(),
    )
    .await?;
    verify_session.disconnect().await;

    // 8. SAVE TO DATABASE
    save_host(
        &db,
        &params,
        &target_private_pem,
        key_type,
        &observed_fp,
        params.host_id,
    )
    .await?;

    // 8b. Update PVE state if detected.
    if is_pve_node {
        let config_id = existing_pve_plugin_config_id.clone();
        if let Err(e) =
            host_ops::update_host_pve_state(&db, &params.host_id.to_string(), true, config_id, None)
                .await
        {
            tracing::warn!(error = %e, "failed to persist PVE state for host");
        }
    }

    // 9. OUTPUT
    println!();
    println!("Bootstrap complete for host '{}'.", params.name);
    println!("  Hostname: {}:{}", params.hostname, params.port);
    println!("  Target user: {}", params.target_username);
    println!("  Key type: {key_type}");
    println!("  Host key: {observed_fp}");
    if is_pve_node {
        println!("  PVE node: yes");
    }

    if generated_key {
        println!();
        println!(
            "NOTE: The Ed25519 private key was generated in memory and is \
             stored only in the encrypted local database. No key file was \
             written to disk."
        );
    }

    println!();
    if sudoers_content.is_some() {
        println!(
            "NOTE: Sudoers file written to /etc/sudoers.d/uptrakit-{}.",
            params.target_username
        );
        println!(
            "      Run 'uptrakit-agent-ssh host update-sudoers {}' to refresh \
             entries when plugins change.",
            params.name
        );
    } else {
        println!("NOTE: No sudoers file was written — no compatible plugin commands were found.");
        println!(
            "      Run 'uptrakit-agent-ssh host update-sudoers {}' after installing \
             supported tools to configure sudo grants.",
            params.name
        );
    }

    Ok(BootstrapResult {
        is_pve_node,
        pve_credentials,
        existing_pve_plugin_config_id,
    })
}

// ── Verification ─────────────────────────────────────────────────────

// ── PVE credential dedup ─────────────────────────────────────────────

/// Check for existing Uptrakit PVE tokens on the cluster and either reuse
/// the existing config or create new credentials.
///
/// Returns `(Some(creds), None)` when new credentials were created,
/// `(None, Some(config_id))` when an existing config was reused, or
/// `(None, None)` when credentials could not be created.
async fn create_or_reuse_pve_credentials(
    executor: &dyn uptrakit_command::RemoteExecutor,
    db: &sea_orm::DatabaseConnection,
    tenant_id: &Option<uuid::Uuid>,
) -> (Option<pve_setup::PveCredentials>, Option<String>) {
    let Some(tid) = tenant_id else {
        println!("  Skipping PVE API credential creation: tenant ID not yet known.");
        println!("  Re-bootstrap this host after the agent has connected to the controller.");
        return (None, None);
    };

    // Check if the cluster already has an Uptrakit API token.
    match pve_setup::check_pve_token_exists(executor, tid).await {
        Ok(pve_setup::PveTokenStatus::OwnedByTenant(user)) => {
            println!("  PVE API user '{user}' already exists on this cluster.");
            println!("  Skipping credential creation.");

            // Try to find an existing PVE host with a config ID to reuse.
            match host_ops::find_pve_host_with_config(db).await {
                Ok(Some(host)) => {
                    let config_id = host
                        .pve_plugin_config_id
                        .expect("find_pve_host_with_config only returns hosts with config");
                    println!("  Reusing plugin config from host '{}'.", host.name);
                    return (None, Some(config_id));
                }
                Ok(None) => {
                    println!("  Warning: no local PVE host has a plugin config ID to reuse.");
                    println!("  Configure the Proxmox plugin manually in the controller UI.");
                    return (None, None);
                }
                Err(e) => {
                    tracing::warn!(error = %e, "failed to look up existing PVE hosts");
                    return (None, None);
                }
            }
        }
        Ok(pve_setup::PveTokenStatus::OwnedByOtherTenant(user)) => {
            println!("  PVE API user '{user}' exists and belongs to a different tenant.");
            println!("  This cluster has already been claimed. Skipping credential creation.");
            return (None, None);
        }
        Ok(pve_setup::PveTokenStatus::NotFound) => {
            // No existing token — proceed with creation below.
        }
        Err(e) => {
            tracing::debug!(error = %e, "PVE token check failed, proceeding with creation");
        }
    }

    // No existing token found — create new credentials.
    println!("Creating PVE API credentials...");
    match pve_setup::create_pve_api_credentials(executor, tid).await {
        Ok(creds) => {
            println!("  API URL: {}", creds.api_url);
            println!("  API token created for {}", pve_setup::pve_user_realm(tid));
            (Some(creds), None)
        }
        Err(e) => {
            tracing::warn!(error = %e, "failed to create PVE API credentials");
            println!("  Warning: could not create PVE API credentials automatically: {e}");
            println!("  You can configure them manually in the Proxmox plugin settings.");
            (None, None)
        }
    }
}

// ── Verification ─────────────────────────────────────────────────────

/// Verify that the remote connection works as `target_username`.
///
/// Always checks `whoami`. When `has_sudo_grants` is `true`, additionally
/// verifies that `sudo -n -l` succeeds — confirming the written sudoers file
/// grants at least one NOPASSWD entry. When `false` (no sudoers file was
/// written) the sudo check is skipped, since there is nothing to verify.
async fn verify_remote(
    session: &SshSession,
    target_username: &str,
    has_sudo_grants: bool,
) -> Result<()> {
    // Verify whoami.
    let whoami = session.exec_command("whoami").await?;
    let actual_user = whoami.stdout.trim();
    if actual_user != target_username {
        bail!(Error::BootstrapVerification(format!(
            "whoami returned '{actual_user}', expected '{target_username}'. \
             The remote host has been partially configured."
        )));
    }

    if has_sudo_grants {
        // Verify sudo. We use `sudo -n -l` (list allowed commands without
        // prompting) rather than `sudo -n true` because the sudoers file may
        // only grant specific commands (e.g. `/usr/bin/apt-get`), not the
        // ability to run arbitrary executables. `-n -l` exits 0 whenever the
        // user has at least one NOPASSWD entry, which is exactly what we want
        // to confirm here.
        let sudo_check = session.exec_command("sudo -n -l").await?;
        if sudo_check.exit_code != 0 {
            bail!(Error::BootstrapVerification(format!(
                "sudo -n -l failed (exit code {}). Sudoers may not be \
                 configured correctly. The remote host has been partially configured.",
                sudo_check.exit_code
            )));
        }
    }

    Ok(())
}

// ── Database save ────────────────────────────────────────────────────

async fn save_host(
    db: &DatabaseConnection,
    params: &BootstrapParams,
    private_pem: &str,
    key_type: crate::db::entity::ssh_host::SshKeyType,
    fingerprint: &str,
    host_id: uuid::Uuid,
) -> Result<()> {
    let encrypted_key =
        EncryptedString::new(private_pem.to_string(), "uptrakit:ssh_hosts:private_key")
            .map_err(|e| report!(Error::Crypto(format!("failed to encrypt private key: {e}"))))?;

    host_ops::add_host(
        db,
        AddHostParams {
            host_id,
            name: params.name.clone(),
            hostname: params.hostname.clone(),
            port: params.port,
            username: params.target_username.clone(),
            encrypted_key,
            key_type,
            host_key_fingerprint: Some(fingerprint.to_string()),
        },
    )
    .await?;

    Ok(())
}

// ── Input validation ─────────────────────────────────────────────────

/// Validate that a string is a valid POSIX username.
///
/// Rules: `[a-z_][a-z0-9_-]*`, max 32 characters.
fn validate_posix_username(username: &str) -> Result<()> {
    if username.is_empty() {
        bail!(Error::InvalidInput(
            "username must not be empty".to_string()
        ));
    }
    if username.len() > MAX_USERNAME_LEN {
        bail!(Error::InvalidInput(format!(
            "username '{}' exceeds maximum length of {MAX_USERNAME_LEN} characters",
            username
        )));
    }

    let mut chars = username.chars();
    let Some(first) = chars.next() else {
        bail!(Error::InvalidInput(
            "username must not be empty".to_string()
        ));
    };
    if !first.is_ascii_lowercase() && first != '_' {
        bail!(Error::InvalidInput(format!(
            "username '{username}' must start with a lowercase letter or underscore"
        )));
    }
    for ch in chars {
        if !ch.is_ascii_lowercase() && !ch.is_ascii_digit() && ch != '_' && ch != '-' {
            bail!(Error::InvalidInput(format!(
                "username '{username}' contains invalid character '{ch}' \
                 (allowed: a-z, 0-9, _, -)"
            )));
        }
    }

    Ok(())
}

// ── Remote command builders ──────────────────────────────────────────

fn cmd_check_user_exists(username: &str, use_sudo: bool) -> String {
    let escaped = uptrakit_command::shell_escape(username);
    if use_sudo {
        format!("sudo id -u {escaped}")
    } else {
        format!("id -u {escaped}")
    }
}

fn cmd_create_user(username: &str, use_sudo: bool) -> String {
    let escaped = uptrakit_command::shell_escape(username);
    if use_sudo {
        format!("sudo useradd --create-home --shell /bin/sh {escaped}")
    } else {
        format!("useradd --create-home --shell /bin/sh {escaped}")
    }
}

fn cmd_detect_home(username: &str, use_sudo: bool) -> String {
    let escaped = uptrakit_command::shell_escape(username);
    if use_sudo {
        format!("sudo getent passwd {escaped} | cut -d: -f6")
    } else {
        format!("getent passwd {escaped} | cut -d: -f6")
    }
}

/// SSH restrictions applied to `authorized_keys` entries.
///
/// These prevent interactive terminal allocation, SSH agent forwarding, and
/// X11 forwarding through the managed account while allowing non-interactive
/// command execution that the agent requires.
const AUTHORIZED_KEYS_RESTRICTIONS: &str = "no-pty,no-agent-forwarding,no-X11-forwarding";

/// Build a remote command that reads `authorized_keys`, tolerating a missing
/// file (returns empty output).
fn cmd_read_authorized_keys(home: &str, use_sudo: bool) -> String {
    let ak_path = format!("{home}/.ssh/authorized_keys");
    let escaped_ak_path = uptrakit_command::shell_escape(&ak_path);
    let sudo_prefix = if use_sudo { "sudo " } else { "" };
    format!("{sudo_prefix}cat {escaped_ak_path} 2>/dev/null || true")
}

/// Build a remote command that atomically overwrites `authorized_keys` with
/// `content` (already-formatted key lines + new entry) and fixes permissions.
fn cmd_write_authorized_keys(home: &str, content: &str, owner: &str, use_sudo: bool) -> String {
    let ak_path = format!("{home}/.ssh/authorized_keys");
    let escaped_ak_path = uptrakit_command::shell_escape(&ak_path);
    let escaped_content = uptrakit_command::shell_escape(content);
    let escaped_owner = uptrakit_command::shell_escape(owner);
    let sudo_prefix = if use_sudo { "sudo " } else { "" };
    format!(
        "printf '%s' {escaped_content} | {sudo_prefix}tee {escaped_ak_path} > /dev/null && \
         {sudo_prefix}chmod 600 {escaped_ak_path} && \
         {sudo_prefix}chown -R {escaped_owner}:{escaped_owner} {home}/.ssh"
    )
}

fn cmd_setup_authorized_keys(
    home: &str,
    pubkey: &str,
    owner: &str,
    use_sudo: bool,
    service_comment: &str,
) -> String {
    let escaped_home = uptrakit_command::shell_escape(home);
    let restricted_key = format!("{AUTHORIZED_KEYS_RESTRICTIONS} {pubkey} {service_comment}");
    let escaped_pubkey = uptrakit_command::shell_escape(&restricted_key);
    let escaped_owner = uptrakit_command::shell_escape(owner);
    let ssh_dir = format!("{home}/.ssh");
    let escaped_ssh_dir = uptrakit_command::shell_escape(&ssh_dir);
    let ak_path = format!("{home}/.ssh/authorized_keys");
    let escaped_ak_path = uptrakit_command::shell_escape(&ak_path);

    let sudo_prefix = if use_sudo { "sudo " } else { "" };

    format!(
        "{sudo_prefix}mkdir -p {escaped_ssh_dir} && \
         {sudo_prefix}chmod 700 {escaped_ssh_dir} && \
         echo {escaped_pubkey} | {sudo_prefix}tee -a {escaped_ak_path} > /dev/null && \
         {sudo_prefix}chmod 600 {escaped_ak_path} && \
         {sudo_prefix}chown -R {escaped_owner}:{escaped_owner} {escaped_home}/.ssh"
    )
}

/// Returns `true` if the `authorized_keys` line looks like a key that was
/// written by Uptrakit.
///
/// Detection: the line is non-empty, does not start with `#`, and its last
/// whitespace-separated token starts with `uptrakit`.
fn is_uptrakit_key_line(line: &str) -> bool {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') {
        return false;
    }
    trimmed
        .split_whitespace()
        .next_back()
        .map(|tok| tok.starts_with("uptrakit"))
        .unwrap_or(false)
}

/// Returns `true` if `line` is an Uptrakit key written by the service with
/// `service_id`.
///
/// Matches comments of the form `uptrakit-svc:<service_id>-host:<host_id>`.
/// Keys with other service UUIDs, plain `uptrakit-host:<host_id>` entries,
/// and non-Uptrakit keys all return `false`.
fn is_same_service_key_line(line: &str, service_id: &uuid::Uuid) -> bool {
    if !is_uptrakit_key_line(line) {
        return false;
    }
    let expected_prefix = format!("uptrakit-svc:{service_id}-host:");
    // `split_whitespace` already skips leading/trailing whitespace, so no
    // explicit `.trim()` is needed here.
    line.split_whitespace()
        .next_back()
        .map(|tok| tok.starts_with(&expected_prefix))
        .unwrap_or(false)
}

/// Classification of the current `authorized_keys` file content.
struct ExistingAuthorizedKeys {
    /// Non-blank, non-comment lines (actual key entries).
    all_key_lines: Vec<String>,
    /// Subset of `all_key_lines` that pass `is_uptrakit_key_line`.
    uptrakit_key_lines: Vec<String>,
}

/// Parse `authorized_keys` content into classified buckets.
fn parse_existing_authorized_keys(content: &str) -> ExistingAuthorizedKeys {
    let mut all_key_lines = Vec::new();
    let mut uptrakit_key_lines = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let owned = trimmed.to_string();
        if is_uptrakit_key_line(trimmed) {
            uptrakit_key_lines.push(owned.clone());
        }
        all_key_lines.push(owned);
    }

    ExistingAuthorizedKeys {
        all_key_lines,
        uptrakit_key_lines,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Username validation tests ────────────────────────────────────

    #[test]
    fn valid_usernames() {
        for name in ["root", "ubuntu", "deploy_user", "a-b-c", "_svc"] {
            assert!(
                validate_posix_username(name).is_ok(),
                "expected valid: {name}"
            );
        }
    }

    #[test]
    fn invalid_username_empty() {
        assert!(validate_posix_username("").is_err());
    }

    #[test]
    fn invalid_username_too_long() {
        let long = "a".repeat(MAX_USERNAME_LEN + 1);
        assert!(validate_posix_username(&long).is_err());
    }

    #[test]
    fn invalid_username_starts_with_digit() {
        assert!(validate_posix_username("1user").is_err());
    }

    #[test]
    fn invalid_username_uppercase() {
        assert!(validate_posix_username("Root").is_err());
    }

    #[test]
    fn invalid_username_special_chars() {
        assert!(validate_posix_username("user@host").is_err());
        assert!(validate_posix_username("user.name").is_err());
    }

    // ── Command builder tests ────────────────────────────────────────

    #[test]
    fn cmd_check_user_exists_with_sudo() {
        let cmd = cmd_check_user_exists("deploy", true);
        assert_eq!(cmd, "sudo id -u 'deploy'");
    }

    #[test]
    fn cmd_check_user_exists_without_sudo() {
        let cmd = cmd_check_user_exists("deploy", false);
        assert_eq!(cmd, "id -u 'deploy'");
    }

    #[test]
    fn cmd_create_user_with_sudo() {
        let cmd = cmd_create_user("uptrakit", true);
        assert_eq!(cmd, "sudo useradd --create-home --shell /bin/sh 'uptrakit'");
    }

    #[test]
    fn cmd_create_user_without_sudo() {
        let cmd = cmd_create_user("uptrakit", false);
        assert_eq!(cmd, "useradd --create-home --shell /bin/sh 'uptrakit'");
    }

    #[test]
    fn cmd_detect_home_with_sudo() {
        let cmd = cmd_detect_home("deploy", true);
        assert_eq!(cmd, "sudo getent passwd 'deploy' | cut -d: -f6");
    }

    #[test]
    fn cmd_shell_escape_prevents_injection() {
        let cmd = cmd_check_user_exists("user'; rm -rf /; echo '", true);
        // The dangerous characters should be escaped inside single quotes.
        assert!(cmd.contains("'user'\\''"));
    }

    #[test]
    fn cmd_authorized_keys_structure() {
        let cmd = cmd_setup_authorized_keys(
            "/home/deploy",
            "ssh-ed25519 AAAA...",
            "deploy",
            true,
            "uptrakit",
        );
        assert!(cmd.contains("mkdir -p"));
        assert!(cmd.contains("chmod 700"));
        assert!(cmd.contains("tee -a"));
        assert!(cmd.contains("chmod 600"));
        assert!(cmd.contains("chown -R"));
        assert!(cmd.contains("no-pty"));
    }

    #[test]
    fn cmd_authorized_keys_includes_restrictions() {
        let cmd =
            cmd_setup_authorized_keys("/home/svc", "ssh-ed25519 AAAA...", "svc", false, "uptrakit");
        assert!(
            cmd.contains("no-pty,no-agent-forwarding,no-X11-forwarding ssh-ed25519"),
            "authorized_keys entry must include restriction prefix: {cmd}"
        );
    }

    #[test]
    fn comment_format_with_host_id_only() {
        let host_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let comment = format!("uptrakit-host:{host_id}");
        let cmd =
            cmd_setup_authorized_keys("/home/svc", "ssh-ed25519 AAAA...", "svc", false, &comment);
        assert!(
            cmd.contains(&comment),
            "authorized_keys entry must contain host comment: {cmd}"
        );
    }

    #[test]
    fn comment_format_with_service_and_host_id() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let host_id = uuid::Uuid::parse_str("018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b").unwrap();
        let comment = format!("uptrakit-svc:{svc_id}-host:{host_id}");
        let cmd =
            cmd_setup_authorized_keys("/home/svc", "ssh-ed25519 AAAA...", "svc", false, &comment);
        assert!(
            cmd.contains(&comment),
            "authorized_keys entry must contain svc+host comment: {cmd}"
        );
    }

    // ── is_uptrakit_key_line tests ───────────────────────────────────

    #[test]
    fn is_uptrakit_key_line_detects_plain_uptrakit() {
        assert!(is_uptrakit_key_line("no-pty ssh-ed25519 AAAA... uptrakit"));
    }

    #[test]
    fn is_uptrakit_key_line_detects_uptrakit_uuid() {
        assert!(is_uptrakit_key_line(
            "no-pty ssh-ed25519 AAAA... uptrakit-550e8400-e29b-41d4-a716-446655440000"
        ));
    }

    #[test]
    fn is_uptrakit_key_line_detects_host_id_comment() {
        assert!(is_uptrakit_key_line(
            "no-pty ssh-ed25519 AAAA... uptrakit-host:018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b"
        ));
    }

    #[test]
    fn is_uptrakit_key_line_detects_svc_and_host_id_comment() {
        assert!(is_uptrakit_key_line(
            "no-pty ssh-ed25519 AAAA... \
             uptrakit-svc:550e8400-e29b-41d4-a716-446655440000-host:018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b"
        ));
    }

    #[test]
    fn is_uptrakit_key_line_rejects_user_at_host() {
        assert!(!is_uptrakit_key_line("ssh-ed25519 AAAA... user@host"));
    }

    #[test]
    fn is_uptrakit_key_line_rejects_blank() {
        assert!(!is_uptrakit_key_line(""));
        assert!(!is_uptrakit_key_line("   "));
    }

    #[test]
    fn is_uptrakit_key_line_rejects_comment_line() {
        assert!(!is_uptrakit_key_line("# uptrakit"));
        assert!(!is_uptrakit_key_line("# ssh-ed25519 AAAA... uptrakit"));
    }

    // ── is_same_service_key_line tests ──────────────────────────────

    #[test]
    fn same_service_key_line_matches_correct_service_and_host() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let host_id = uuid::Uuid::parse_str("018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b").unwrap();
        let line = format!(
            "no-pty,no-agent-forwarding,no-X11-forwarding ssh-ed25519 AAAA... \
             uptrakit-svc:{svc_id}-host:{host_id}"
        );
        assert!(is_same_service_key_line(&line, &svc_id));
    }

    #[test]
    fn same_service_key_line_rejects_different_service() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let other_svc = uuid::Uuid::parse_str("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee").unwrap();
        let host_id = uuid::Uuid::parse_str("018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b").unwrap();
        let line = format!("no-pty ssh-ed25519 AAAA... uptrakit-svc:{other_svc}-host:{host_id}");
        assert!(!is_same_service_key_line(&line, &svc_id));
    }

    #[test]
    fn same_service_key_line_rejects_host_only_comment() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let host_id = uuid::Uuid::parse_str("018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b").unwrap();
        // uptrakit-host: format has no service prefix — must not match
        let line = format!("no-pty ssh-ed25519 AAAA... uptrakit-host:{host_id}");
        assert!(!is_same_service_key_line(&line, &svc_id));
    }

    #[test]
    fn same_service_key_line_rejects_non_uptrakit_key() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        assert!(!is_same_service_key_line(
            "ssh-ed25519 AAAA... user@host",
            &svc_id
        ));
    }

    #[test]
    fn same_service_key_line_rejects_blank() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        assert!(!is_same_service_key_line("", &svc_id));
        assert!(!is_same_service_key_line("   ", &svc_id));
    }

    #[test]
    fn same_service_key_line_rejects_comment_line() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let host_id = uuid::Uuid::parse_str("018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b").unwrap();
        let line = format!("# uptrakit-svc:{svc_id}-host:{host_id}");
        assert!(!is_same_service_key_line(&line, &svc_id));
    }

    #[test]
    fn same_service_key_line_matches_any_host_id_for_same_service() {
        let svc_id = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        for host_id in [
            "018d7f12-3e4a-7000-b1a9-4d8e6c0f2a1b",
            "11111111-2222-3333-4444-555555555555",
            "ffffffff-ffff-ffff-ffff-ffffffffffff",
        ] {
            let line = format!("no-pty ssh-ed25519 AAAA... uptrakit-svc:{svc_id}-host:{host_id}");
            assert!(
                is_same_service_key_line(&line, &svc_id),
                "should match host_id={host_id}"
            );
        }
    }

    // ── parse_existing_authorized_keys tests ────────────────────────

    #[test]
    fn parse_empty_file() {
        let result = parse_existing_authorized_keys("");
        assert!(result.all_key_lines.is_empty());
        assert!(result.uptrakit_key_lines.is_empty());
    }

    #[test]
    fn parse_no_uptrakit_keys() {
        let content = "ssh-ed25519 AAAA... user@host\nssh-rsa BBBB... admin@server\n";
        let result = parse_existing_authorized_keys(content);
        assert_eq!(result.all_key_lines.len(), 2);
        assert!(result.uptrakit_key_lines.is_empty());
    }

    #[test]
    fn parse_mixed_keys() {
        let content = "ssh-ed25519 AAAA... user@host\n\
                       no-pty ssh-ed25519 BBBB... uptrakit\n\
                       ssh-rsa CCCC... admin@server\n\
                       no-pty ssh-ed25519 DDDD... uptrakit-550e8400-e29b-41d4-a716-446655440000\n";
        let result = parse_existing_authorized_keys(content);
        assert_eq!(result.all_key_lines.len(), 4);
        assert_eq!(result.uptrakit_key_lines.len(), 2);
        assert!(
            result
                .uptrakit_key_lines
                .iter()
                .all(|l| l.ends_with("uptrakit") || l.contains("uptrakit-"))
        );
    }

    #[test]
    fn parse_comment_only_lines_ignored() {
        let content = "# This is a comment\n\
                       # uptrakit key\n\
                       ssh-ed25519 AAAA... uptrakit\n";
        let result = parse_existing_authorized_keys(content);
        assert_eq!(result.all_key_lines.len(), 1);
        assert_eq!(result.uptrakit_key_lines.len(), 1);
    }

    #[test]
    fn parse_blank_lines_ignored() {
        let content = "\n\n  \nssh-ed25519 AAAA... uptrakit\n\n";
        let result = parse_existing_authorized_keys(content);
        assert_eq!(result.all_key_lines.len(), 1);
        assert_eq!(result.uptrakit_key_lines.len(), 1);
    }

    // ── cmd_read_authorized_keys tests ──────────────────────────────

    #[test]
    fn cmd_read_authorized_keys_without_sudo() {
        let cmd = cmd_read_authorized_keys("/home/uptrakit", false);
        assert!(!cmd.contains("sudo"));
        assert!(cmd.contains("/home/uptrakit/.ssh/authorized_keys"));
        assert!(cmd.contains("2>/dev/null || true"));
    }

    #[test]
    fn cmd_read_authorized_keys_with_sudo() {
        let cmd = cmd_read_authorized_keys("/home/uptrakit", true);
        assert!(cmd.starts_with("sudo "));
        assert!(cmd.contains("/home/uptrakit/.ssh/authorized_keys"));
    }

    // ── cmd_write_authorized_keys tests ─────────────────────────────

    #[test]
    fn cmd_write_authorized_keys_structure() {
        let content = "no-pty ssh-ed25519 AAAA... uptrakit\n";
        let cmd = cmd_write_authorized_keys("/home/uptrakit", content, "uptrakit", true);
        assert!(cmd.contains("printf '%s'"));
        assert!(cmd.contains("sudo tee"));
        assert!(cmd.contains("/home/uptrakit/.ssh/authorized_keys"));
        assert!(cmd.contains("chmod 600"));
        assert!(cmd.contains("chown -R"));
    }

    #[test]
    fn cmd_write_authorized_keys_without_sudo() {
        let content = "no-pty ssh-ed25519 AAAA... uptrakit\n";
        let cmd = cmd_write_authorized_keys("/home/deploy", content, "deploy", false);
        assert!(!cmd.contains("sudo"));
        assert!(cmd.contains("tee"));
    }

    #[test]
    fn cmd_write_authorized_keys_escapes_content() {
        // Content with single-quotes should be safely escaped.
        let content = "no-pty ssh-ed25519 AAAA it's uptrakit\n";
        let cmd = cmd_write_authorized_keys("/home/deploy", content, "deploy", false);
        // shell_escape wraps in single quotes and escapes embedded single-quotes.
        assert!(
            !cmd.contains("it's"),
            "raw single quote must not appear unescaped: {cmd}"
        );
    }
}
