[workspace]
publish = false
git_release_enable = false

[[package]]
name = "uptrakit-controller"
git_release_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "uptrakit v{{ version }}"
