[package]
name = "uptrakit-plugin-infrastructure-registry"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = ["daemon"]
daemon = ["uptrakit-plugin-releases-docker/daemon"]
ssh = ["daemon", "uptrakit-plugin-releases-docker/ssh"]

[dependencies]
uptrakit-shared-types = { workspace = true }
uptrakit-command = { workspace = true }
uptrakit-plugin-infrastructure-core = { workspace = true }
uptrakit-plugin-releases-github = { path = "../../releases/github" }
uptrakit-plugin-releases-gitlab = { path = "../../releases/gitlab" }
uptrakit-plugin-releases-forgejo = { path = "../../releases/forgejo" }
uptrakit-plugin-releases-docker = { path = "../../releases/docker" }
uptrakit-plugin-discovery-proxmox-helper-scripts = { path = "../../discovery/proxmox-helper-scripts" }
uptrakit-plugin-package-manager-homebrew = { path = "../../package-managers/homebrew" }
uptrakit-plugin-package-manager-apt = { path = "../../package-managers/apt" }
uptrakit-plugin-package-manager-npm = { path = "../../package-managers/npm" }
uptrakit-plugin-generic-shell = { path = "../../generic/shell" }
serde_json = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
