[package]
name = "uptrakit-plugin-infrastructure-registry"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = ["daemon"]
daemon = ["uptrakit-plugin-releases-docker/daemon"]
ssh = ["daemon", "uptrakit-plugin-releases-docker/ssh"]

[dependencies]
uptrakit-shared-types = { workspace = true }
uptrakit-command = { workspace = true }
uptrakit-plugin-infrastructure-core = { workspace = true }
uptrakit-plugin-releases-github = { workspace = true }
uptrakit-plugin-releases-gitlab = { workspace = true }
uptrakit-plugin-releases-forgejo = { workspace = true }
uptrakit-plugin-releases-docker = { workspace = true }
uptrakit-plugin-discovery-proxmox-helper-scripts = { workspace = true }
uptrakit-plugin-package-manager-homebrew = { workspace = true }
uptrakit-plugin-package-manager-apt = { workspace = true }
uptrakit-plugin-package-manager-npm = { workspace = true }
uptrakit-plugin-package-manager-mas = { workspace = true }
uptrakit-plugin-generic-shell = { workspace = true }
uptrakit-internal-wire = { workspace = true }
futures-util = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
