[package]
name = "uptrakit-mqtt"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "uptrakit-mqtt"
path = "src/main.rs"

[features]
default = []

[dependencies]
clap = { workspace = true }
futures-util = { workspace = true }
hostname = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
rumqttc = { version = "0.25.1" }
rustls = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uptrakit-directories = { path = "../../shared/directories" }
uptrakit-enrollment = { path = "../../shared/enrollment" }
uptrakit-internal-wire = { path = "../../shared/wire" }
uptrakit-web-api-types = { path = "../../shared/web-api-types" }
uuid = { workspace = true }
webpki-roots = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
