[package]
name = "uptrakit-plugin-docker"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = []
ssh = ["bollard/ssh"]

[dependencies]
uptrakit-plugin-core = { path = "../core" }
bollard      = { workspace = true, features = ["ssl"] }
futures-util = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
uptrakit-command = { path = "../../shared/command" }
