use totp_rs::{Algorithm, Secret, TOTP};

/// Generate a new TOTP base32 secret suitable for storing in the DB.
pub fn generate_totp_secret() -> String {
    Secret::generate_secret().to_encoded().to_string()
}

/// Build the `otpauth://totp/` URI to encode into a QR code.
/// Returns `None` if the secret is not valid base32 (should not happen — secrets are
/// generated by `generate_totp_secret()` which produces valid base32).
pub fn build_otpauth_uri(secret: &str, user_email: &str, issuer: &str) -> Option<String> {
    build_totp_with_issuer(secret, Some(issuer.to_string()), user_email)
        .ok()
        .map(|totp| totp.get_url())
}

/// Verify a 6-digit TOTP code with skew=1 (±30 s window).
///
/// Returns `Some(step)` — the TOTP counter index the code matched — on success,
/// or `None` on failure. Callers must persist `step` in `user_totp.last_used_step`
/// and reject any future code with `step <= last_used_step` (RFC 6238 §5.2 replay prevention).
pub fn verify_totp_code(secret: &str, code: &str) -> Option<i64> {
    let Ok(totp) = build_totp(secret) else {
        return None;
    };
    let now_secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_secs();
    let current_step = (now_secs / 30) as i64;
    for delta in [-1i64, 0, 1] {
        let step = current_step + delta;
        if step < 0 {
            continue;
        }
        let step_time = (step as u64) * 30;
        let expected = totp.generate(step_time);
        if expected == code {
            return Some(step);
        }
    }
    None
}

fn build_totp(secret: &str) -> Result<TOTP, totp_rs::TotpUrlError> {
    build_totp_with_issuer(secret, None, "")
}

fn build_totp_with_issuer(
    secret: &str,
    issuer: Option<String>,
    account_name: &str,
) -> Result<TOTP, totp_rs::TotpUrlError> {
    let bytes = Secret::Encoded(secret.to_string())
        .to_bytes()
        .map_err(|_err| totp_rs::TotpUrlError::Secret("invalid base32".to_string()))?;
    TOTP::new(
        Algorithm::SHA1,
        6,
        1,
        30,
        bytes,
        issuer,
        account_name.to_string(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_secret_returns_base32_string() {
        let secret = generate_totp_secret();
        assert!(
            secret
                .chars()
                .all(|c| c.is_ascii_uppercase() || matches!(c, '2'..='7'))
        );
        assert!(secret.len() >= 16);
    }

    #[test]
    fn build_otpauth_uri_contains_issuer_and_email() {
        let uri = build_otpauth_uri(
            "JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP",
            "alice@example.com",
            "uptrakit",
        );
        assert!(uri.is_some());
        let uri_str = uri.unwrap();
        assert!(uri_str.contains("alice%40example.com") || uri_str.contains("alice@example.com"));
        assert!(uri_str.contains("uptrakit"));
        assert!(uri_str.starts_with("otpauth://totp/"));
    }

    #[test]
    fn verify_totp_accepts_current_code() {
        let secret = generate_totp_secret();
        let totp = TOTP::new(
            Algorithm::SHA1,
            6,
            1,
            30,
            Secret::Encoded(secret.clone()).to_bytes().unwrap(),
            None,
            "test@example.com".to_string(),
        )
        .unwrap();
        let code = totp.generate_current().unwrap();
        assert!(verify_totp_code(&secret, &code).is_some());
    }

    #[test]
    fn verify_totp_rejects_wrong_code() {
        let secret = generate_totp_secret();
        assert!(verify_totp_code(&secret, "000000").is_none());
    }
}
