use totp_rs::{Algorithm, Builder, Secret, Totp};

/// TOTP step duration in seconds (RFC 6238 default).
const STEP_SECS: u64 = 30;

/// Generate a new TOTP base32 secret suitable for storing in the DB.
pub fn generate_totp_secret() -> String {
    Secret::generate().to_base32()
}

/// Build the `otpauth://totp/` URI to encode into a QR code.
/// Returns `None` if the secret is not valid base32 (should not happen — secrets are
/// generated by `generate_totp_secret()` which produces valid base32).
pub fn build_otpauth_uri(secret: &str, user_email: &str, issuer: &str) -> Option<String> {
    build_totp_with_issuer(secret, Some(issuer.to_string()), user_email)?
        .to_url()
        .ok()
}

/// Generate the current TOTP code for a given secret.
///
/// Returns `None` if the secret is not valid base32 or if the system clock
/// is unavailable.
pub fn generate_totp_code(secret: &str) -> Option<String> {
    let totp = build_totp(secret)?;
    Some(totp.generate(unix_now_secs()?).to_string())
}

/// Verify a 6-digit TOTP code with skew=1 (±30 s window).
///
/// Returns `Some(step)` — the TOTP counter index the code matched — on success,
/// or `None` on failure. Callers must persist `step` in `user_totp.last_used_step`
/// and reject any future code with `step <= last_used_step` (RFC 6238 §5.2 replay prevention).
pub fn verify_totp_code(secret: &str, code: &str) -> Option<i64> {
    let totp = build_totp(secret)?;
    // `check` walks `origin - skew ..= origin + skew` and compares in constant time,
    // returning the counter index that matched — the same value the caller stores as
    // `last_used_step`.
    let step = totp.check(code, unix_now_secs()?)?;
    i64::try_from(step).ok()
}

fn unix_now_secs() -> Option<u64> {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()
        .map(|elapsed| elapsed.as_secs())
}

fn build_totp(secret: &str) -> Option<Totp> {
    build_totp_with_issuer(secret, None, "")
}

/// Returns `None` when the secret is not valid base32 or fails RFC 6238 validation
/// (shorter than 128 bits, or an issuer/account name containing `:`).
fn build_totp_with_issuer(
    secret: &str,
    issuer: Option<String>,
    account_name: &str,
) -> Option<Totp> {
    let secret = Secret::try_from_base32(secret).ok()?;
    Builder::new()
        .with_algorithm(Algorithm::SHA1)
        .with_digits(6)
        .with_skew(1)
        .with_step_duration(STEP_SECS)
        .with_secret(secret)
        .with_issuer(issuer)
        .with_account_name(account_name)
        .build()
        .ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// RFC 6238 Appendix B test vector: the 20-byte ASCII secret `12345678901234567890`
    /// as unpadded base32, which is also the shape `generate_totp_secret()` emits.
    const RFC6238_SECRET_BASE32: &str = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";

    #[test]
    fn generate_secret_returns_base32_string() {
        let secret = generate_totp_secret();
        assert!(
            secret
                .chars()
                .all(|c| c.is_ascii_uppercase() || matches!(c, '2'..='7'))
        );
        assert!(secret.len() >= 16);
    }

    #[test]
    fn build_otpauth_uri_contains_issuer_and_email() {
        let uri = build_otpauth_uri(
            "JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP",
            "alice@example.com",
            "uptrakit",
        );
        assert!(uri.is_some());
        let uri_str = uri.unwrap();
        assert!(uri_str.contains("alice%40example.com") || uri_str.contains("alice@example.com"));
        assert!(uri_str.contains("uptrakit"));
        assert!(uri_str.starts_with("otpauth://totp/"));
    }

    #[test]
    fn verify_totp_accepts_current_code() {
        let secret = generate_totp_secret();
        let code = generate_totp_code(&secret).expect("generated secret must be valid base32");
        assert!(verify_totp_code(&secret, &code).is_some());
    }

    #[test]
    fn verify_totp_rejects_wrong_code() {
        let secret = generate_totp_secret();
        assert!(verify_totp_code(&secret, "000000").is_none());
    }

    /// Secrets already stored in `user_totp.secret` were produced by totp-rs 5, which encoded
    /// them as unpadded RFC 4648 base32. This pins the decode + code-derivation path against the
    /// RFC 6238 vector rather than against the library itself, so a future upgrade that silently
    /// changed either step would fail here instead of invalidating every enrolled user's 2FA.
    #[test]
    fn stored_secret_still_derives_rfc6238_codes() {
        let totp = build_totp(RFC6238_SECRET_BASE32).expect("RFC 6238 secret must decode");
        // RFC 6238 Appendix B, T = 59 s, SHA-1: 8-digit code 94287082 → 6 digits 287082.
        assert_eq!(totp.generate(59).to_string(), "287082");
        // T = 1111111109 → 8-digit 07081804 → 6 digits 081804.
        assert_eq!(totp.generate(1_111_111_109).to_string(), "081804");
    }

    /// `check` must accept a code minted for the same counter, and report that counter back so
    /// callers can persist it as `last_used_step`.
    #[test]
    fn verify_returns_the_matched_step() {
        let totp = build_totp(RFC6238_SECRET_BASE32).expect("RFC 6238 secret must decode");
        let code = totp.generate(59).to_string();
        assert_eq!(totp.check(&code, 59), Some(59 / STEP_SECS));
    }

    /// Both totp-rs 5 and 6 encode and decode with `Rfc4648 { padding: false }`, whose inverse
    /// table has no entry for `=`, so a padded secret is rejected by either version. No stored
    /// secret can contain padding — v5 never emitted it — and this pins that the decoder stayed
    /// padding-free rather than silently widening.
    #[test]
    fn padded_base32_secret_is_rejected() {
        let padded = "JBSWY3DPEHPK3PXPJBSWY3DPEH======";
        assert!(padded.ends_with('='));
        assert!(build_totp(padded).is_none());
        assert!(!generate_totp_secret().contains('='));
    }
}
