[package]
name = "uptrakit-enrollment"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
futures-util = { workspace = true }
hostname = { workspace = true }
http = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-tungstenite = { version = "0.28", default-features = false, features = ["connect"] }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
webpki-roots = { workspace = true }
x509-parser = { workspace = true }
uptrakit-directories = { path = "../directories" }
uptrakit-internal-wire = { path = "../wire" }

[dev-dependencies]
tempfile = "3"
