[package]
name = "uptrakit-web-api-types"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
description = "Shared HTTP request/response types for the Uptrakit web API"

[features]
default = []
openapi = ["dep:utoipa"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uptrakit-internal-wire = { path = "../wire" }
uptrakit-shared-types = { workspace = true, features = ["openapi"] }
uuid = { workspace = true, features = ["serde"] }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
strum = { workspace = true }
