[package]
name = "uptrakit-tracing-init"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[features]
cli = []
test-support = []

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }

[lints]
workspace = true
