[package]
name = "uptrakit-tracing-init"
description = "Uptrakit shared tracing-init: unified tracing-subscriber setup"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
version = "0.0.1"

[features]
cli = []
test-support = []

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }

[lints]
workspace = true
