[package]
name = "uptrakit-plugin-package-manager-cargo"
description = "Uptrakit package-manager plugin for Rust cargo binstall"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["http-client"] }
uptrakit-shared-types = { workspace = true }
rootcause = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uptrakit-shared-macros = { workspace = true }
time = { workspace = true }
reqwest = { workspace = true }
tame-index = { workspace = true }
futures-util = { workspace = true, features = ["alloc"] }

[dev-dependencies]
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt"] }
uptrakit-command = { workspace = true }

[lints]
workspace = true
