[package]
name = "uptrakit-notification-plugin-telegram"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false
description = "Telegram notification plugin for Uptrakit"

[dependencies]
async-trait = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uptrakit-notification-plugin-core = { path = "../core" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
serde_json = { workspace = true }

[lints]
workspace = true
