[package]
name = "uptrakit-plugin-discovery-proxmox-helper-scripts"
description = "Uptrakit discovery plugin for Proxmox VE helper-scripts community catalog"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
version = "0.0.4"

[dependencies]
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["http-client"] }
uptrakit-command = { workspace = true }
uptrakit-shared-macros = { workspace = true }
rootcause = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
uptrakit-shared-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "net", "io-util"] }
uptrakit-plugin-infrastructure-core = { workspace = true, features = ["testing"] }

[lints]
workspace = true
