[package]
name = "uptrakit-command"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["process", "io-util", "sync", "rt", "macros", "time"] }
uptrakit-shared-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
