[package]
name = "uptrakit-plugin-releases-docker"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = ["daemon"]
daemon = ["dep:bollard", "dep:futures-util", "dep:tokio"]
ssh = ["daemon", "bollard/ssh"]

[dependencies]
uptrakit-plugin-infrastructure-core = { workspace = true }
uptrakit-shared-types = { workspace = true }
bollard      = { workspace = true, features = ["aws-lc-rs"], optional = true }
futures-util = { workspace = true, optional = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "rt", "fs"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
uptrakit-command = { workspace = true }

[lints]
workspace = true
