[package]
name = "uptrakit-shared-types"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
sea-orm = ["dep:sea-orm"]
openapi = ["dep:utoipa"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
sea-orm = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
zeroize = { workspace = true }

[dev-dependencies]
husky-rs = { workspace = true }

[lints]
workspace = true
