[package]
name = "uptrakit-directories"
version.workspace = true
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
directories = "6"
rootcause.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
