[package]
name = "uptrakit-directories"
version.workspace = true
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
directories = "6"
rootcause.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
