#!/usr/bin/env bash
# Regenerate docs/adr/README.md (ADR table of contents).
#
# Filename-keyed on purpose: `adrs generate toc` derives link targets from
# title slugs, which breaks on this corpus's pre-existing filenames (see the
# adrs-adoption ADR). Links here are the literal filenames, so they cannot
# go stale while the staleness check passes.
#
# Usage:
#   scripts/regen-adr-toc.sh           regenerate docs/adr/README.md in place
#   scripts/regen-adr-toc.sh --check   exit 1 if the committed file is stale
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="docs/adr/README.md"

generate() {
  printf '# Architecture Decision Records\n\n'
  printf '<!-- Generated by scripts/regen-adr-toc.sh — do not edit by hand. -->\n\n'
  local f title
  for f in docs/adr/[0-9]*.md; do
    title=$(head -1 "$f")
    title=${title#\# }
    # escape brackets so a future title like "Fix [urgent] X" stays a valid link
    title=${title//\[/\\[}
    title=${title//\]/\\]}
    printf -- '- [%s](%s)\n' "$title" "$(basename "$f")"
  done
}

check_links() {  # tripwire against generator bugs — filename links must resolve
  local target
  while IFS= read -r target; do
    if [[ ! -e "docs/adr/$target" ]]; then
      echo "regen-adr-toc: broken link target: $target"
      return 1
    fi
  done < <(sed -nE 's/^- \[.*\]\((.*)\)$/\1/p' "$OUT")
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$OUT" <(generate); then
    echo "regen-adr-toc: $OUT is stale — run scripts/regen-adr-toc.sh and commit the result."
    exit 1
  fi
  check_links
  echo "regen-adr-toc: OK"
else
  generate >"$OUT"
  check_links
  echo "Regenerated $OUT"
fi
