[package]
name = "uptrakit-internal-wire"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
uptrakit-provider-core = { path = "../../providers/core" }