[package]
name = "uptrakit-provider-registry"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
uptrakit-shared-types = { path = "../../shared/types" }
uptrakit-command = { path = "../../shared/command" }
uptrakit-provider-core = { path = "../core" }
uptrakit-provider-github = { path = "../github" }
uptrakit-provider-docker-registry = { path = "../docker-registry" }
uptrakit-provider-proxmox-helper-scripts = { path = "../proxmox-helper-scripts" }
uptrakit-provider-homebrew = { path = "../homebrew" }
serde_json = { workspace = true }
thiserror = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
