[package]
name = "uptrakit-agent-core"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = []
ssh = ["uptrakit-plugin-infrastructure-registry/ssh"]

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v7", "serde"] }
uptrakit-command = { workspace = true }
uptrakit-internal-wire = { path = "../wire" }
uptrakit-plugin-infrastructure-core = { workspace = true }
uptrakit-plugin-infrastructure-registry = { workspace = true, features = ["daemon"] }
uptrakit-service-sdk = { path = "../service-sdk" }
uptrakit-directories = { path = "../directories" }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
