[package]
name = "uptrakit-agent-core"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
default = []

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
rootcause = { workspace = true }
uptrakit-shared-macros = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v7", "serde"] }
reqwest = { workspace = true }
serde = { workspace = true }
uptrakit-backoff = { workspace = true }
uptrakit-command = { workspace = true }
uptrakit-internal-wire = { workspace = true }
uptrakit-plugin-infrastructure-core = { workspace = true }
uptrakit-plugin-infrastructure-registry = { workspace = true, features = ["daemon"] }
uptrakit-service-sdk = { workspace = true }
uptrakit-directories = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[lints]
workspace = true
